export const arch_style_pic = ({
  client_id,
  load_img,
  text,
  negative,
  ipadapter_obj,
  ipadapter_imgs,
  cn_strength,
  imgSize,
  sampler_name,
  scheduler,
  steps,
  cfg,
  lora1_weight,
  lora1_clip,
  lora2_weight,
  lora2_clip,
  ckpt,
  lora1_name,
  lora2_name,
}: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = text.replaceAll('，', ',');
  const negative_prompt = negative.replaceAll('，', ',');
  console.log('arch_style_pic', {
    client_id,
    load_img,
    text,
    negative,
    ipadapter_obj,
    ipadapter_imgs,
    cn_strength,
    input_seed,
    prompt,
    negative_prompt,
    imgSize,
    sampler_name,
    scheduler,
    steps,
    cfg,
    lora1_weight,
    lora1_clip,
    lora2_weight,
    lora2_clip,
    ckpt,
    lora1_name,
    lora2_name,
  });
  return {
    client_id: client_id,
    prompt: {
      '70': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_canny.pth',
          controlnet_strength_1: 1,
          start_percent_1: 0,
          end_percent_1: 1,
          switch_2: 'Off',
          controlnet_2: 'control_v11p_sd15_soft.pth',
          controlnet_strength_2: 1,
          start_percent_2: 0,
          end_percent_2: 1,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.15,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_3: ['75', 0],
          controlnet_stack: ['71', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '71': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_mlsd.pth',
          controlnet_strength_1: 0.5,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'On',
          controlnet_2: 'control_v11p_sd15_seg.pth',
          controlnet_strength_2: 0.15,
          start_percent_2: 0,
          end_percent_2: 0.6,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_3: cn_strength.strength,
          start_percent_3: 0,
          end_percent_3: cn_strength.end,
          image_2: ['76', 0],
          image_3: ['72', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '72': {
        inputs: { coarse: 'enable', resolution: imgSize, image: ['77', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '75': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '76': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'OneFormer-COCO-SemSegPreprocessor',
      },
      '77': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '79': {
        inputs: {
          switch: 'On',
          base_positive: ['83', 0],
          base_negative: ['84', 0],
          controlnet_stack: ['100', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '80': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
      '81': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'Eva-GT.safetensors',
          model_weight_1: 0.15,
          clip_weight_1: 2,
          switch_2: lora1_name == 'None' ? 'Off' : 'On',
          lora_name_2: lora1_name,
          model_weight_2: lora1_weight,
          clip_weight_2: lora1_clip,
          switch_3: lora2_name == 'None' ? 'Off' : 'On',
          lora_name_3: lora2_name,
          model_weight_3: lora2_weight,
          clip_weight_3: lora2_clip,
        },
        class_type: 'CR LoRA Stack',
      },
      '82': {
        inputs: { model: ['107', 0], clip: ['80', 1], lora_stack: ['103', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '83': {
        inputs: {
          text: prompt,
          clip: ['82', 1],
        },
        class_type: 'CLIPTextEncode',
      },
      '84': { inputs: { text: ['117', 0], clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
      '86': {
        inputs: { ipadapter_file: 'ip_adapter-plus.bin' },
        class_type: 'IPAdapterModelLoader',
      },
      '89': {
        inputs: {
          seed: input_seed,
          steps: steps,
          cfg: cfg,
          sampler_name: sampler_name,
          scheduler: scheduler,
          denoise: 1,
          model: ['82', 0],
          positive: ['79', 0],
          negative: ['79', 1],
          latent_image: ['91', 0],
        },
        class_type: 'KSampler',
      },
      '91': { inputs: { pixels: ['72', 0], vae: ['80', 2] }, class_type: 'VAEEncode' },
      '93': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '94': { inputs: { samples: ['89', 0], vae: ['93', 0] }, class_type: 'VAEDecode' },
      '100': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_normalbae.pth',
          controlnet_strength_1: 0.5,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'Off',
          controlnet_2: 'None',
          controlnet_strength_2: 1,
          start_percent_2: 0,
          end_percent_2: 1,
          switch_3: 'Off',
          controlnet_3: 'None',
          controlnet_strength_3: 1,
          start_percent_3: 0,
          end_percent_3: 1,
          controlnet_stack: ['70', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '103': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 1,
          clip_weight_1: 1,
          switch_2: 'Off',
          lora_name_2: 'None',
          model_weight_2: 1,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 1,
          clip_weight_3: 1,
          lora_stack: ['81', 0],
        },
        class_type: 'CR LoRA Stack',
      },
      '104': {
        inputs: {
          ipadapter_plus: true,
          noise: 1,
          weight_1: 1,
          weight_2: 1,
          weight_3: 1,
          weight_4: 1,
          clip_vision: ['105', 0],
          image_1: ['109', 0],
        },
        class_type: 'IPAdapterEncoder',
      },
      '105': { inputs: { clip_name: 'SD1.5\\pytorch_model.bin' }, class_type: 'CLIPVisionLoader' },
      '107': {
        inputs: {
          weight: 0.8,
          weight_type: 'original',
          start_at: 0,
          end_at: 1,
          unfold_batch: false,
          ipadapter: ['86', 0],
          embeds: ['104', 0],
          model: ['80', 0],
        },
        class_type: 'IPAdapterApplyEncoded',
      },
      '109': {
        inputs: { image: ipadapter_imgs[0].img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '116': { inputs: { filename_prefix: 'Eva', images: ['94', 0] }, class_type: 'SaveImage' },
      '117': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: false,
          text: negative_prompt,
        },
        class_type: 'EmbeddingPicker',
      },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 117,
          last_link_id: 248,
          nodes: [
            {
              id: 82,
              type: 'CR Apply LoRA Stack',
              pos: [-2616, 85],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 232 },
                { name: 'clip', type: 'CLIP', link: 185 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 224 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [196], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [186, 187], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 91,
              type: 'VAEEncode',
              pos: [-2249, 1247],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 222 },
                { name: 'vae', type: 'VAE', link: 217, slot_index: 1 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [216], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 79,
              type: 'CR Apply Multi-ControlNet',
              pos: [-400, 743],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 22,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 188 },
                { name: 'base_negative', type: 'CONDITIONING', link: 189 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 212 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [195], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [198], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 103,
              type: 'CR LoRA Stack',
              pos: [-2301, -377],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: 223 }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [224], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: ['Off', 'None', 1, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
            },
            {
              id: 105,
              type: 'CLIPVisionLoader',
              pos: [-3711, -835],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [
                { name: 'CLIP_VISION', type: 'CLIP_VISION', links: [225], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'CLIPVisionLoader' },
              widgets_values: ['SD1.5\\pytorch_model.bin'],
            },
            {
              id: 80,
              type: 'CheckpointLoaderSimple',
              pos: [-2641, -577],
              size: { '0': 315, '1': 98 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [231], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [185], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [217], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: ['Eva_AI.safetensors'],
            },
            {
              id: 72,
              type: 'LineArtPreprocessor',
              pos: [-1684, 321],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 175 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [176, 222], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['enable', imgSize],
            },
            {
              id: 76,
              type: 'OneFormer-COCO-SemSegPreprocessor',
              pos: [-1970, 209],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 170 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [174], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'OneFormer-COCO-SemSegPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 100,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1030, 457],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: null },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 211, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [212],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_normalbae.pth',
                0.5,
                0,
                0.6,
                'Off',
                'None',
                1,
                0,
                1,
                'Off',
                'None',
                1,
                0,
                1,
              ],
            },
            {
              id: 93,
              type: 'VAELoader',
              pos: [-1867, 1001],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [204], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 90,
              type: 'Reroute',
              pos: [-2582, 893],
              size: [75, 26],
              flags: {},
              order: 19,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 196 }],
              outputs: [{ name: '', type: 'MODEL', links: [197], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 75,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1431, 213],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 172 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [180], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 70,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1502, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: 180 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 168, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [211],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_canny.pth',
                1,
                0,
                1,
                'Off',
                'control_v11p_sd15_soft.pth',
                1,
                0,
                1,
                'On',
                'control_v11p_sd15_depth.pth',
                0.15,
                0,
                0.6,
              ],
            },
            {
              id: 71,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1996, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: 174 },
                { name: 'image_3', type: 'IMAGE', link: 176 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null, slot_index: 3 },
              ],
              outputs: [
                { name: 'CONTROLNET_STACK', type: 'CONTROL_NET_STACK', links: [168], shape: 3 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_mlsd.pth',
                0.5,
                0,
                0.6,
                'On',
                'control_v11p_sd15_seg.pth',
                0.15,
                0,
                0.6,
                'On',
                'control_v11p_sd15_lineart.pth',
                cn_strength.strength,
                0,
                cn_strength.end,
              ],
            },
            {
              id: 83,
              type: 'CLIPTextEncode',
              pos: [-2630, 234],
              size: { '0': 342.46282958984375, '1': 114.1131362915039 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [{ name: 'clip', type: 'CLIP', link: 186 }],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [188],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [prompt],
            },
            {
              id: 77,
              type: 'LoadImage',
              pos: [-936, 1634],
              size: { '0': 487.04541015625, '1': 452.845458984375 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [170, 172, 175], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 89,
              type: 'KSampler',
              pos: [-1786, 1211],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 23,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 197 },
                { name: 'positive', type: 'CONDITIONING', link: 195 },
                { name: 'negative', type: 'CONDITIONING', link: 198 },
                { name: 'latent_image', type: 'LATENT', link: 216, slot_index: 3 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [203], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', steps, cfg, sampler_name, scheduler, 1],
            },
            {
              id: 81,
              type: 'CR LoRA Stack',
              pos: [-2655, -375],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 4,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [223], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: [
                'Off',
                'Eva-GT.safetensors',
                0.15,
                2,
                lora1_name == 'None' ? 'Off' : 'On',
                lora1_name,
                lora1_weight,
                lora1_clip,
                lora2_name == 'None' ? 'Off' : 'On',
                lora2_name,
                lora2_weight,
                lora2_clip,
              ],
            },
            {
              id: 94,
              type: 'VAEDecode',
              pos: [-1371, 1319],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 24,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 203 },
                { name: 'vae', type: 'VAE', link: 204, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [246], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 86,
              type: 'IPAdapterModelLoader',
              pos: [-3714, -730],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'IPADAPTER', type: 'IPADAPTER', links: [228], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'IPAdapterModelLoader' },
              widgets_values: ['ip_adapter-plus.bin'],
            },
            {
              id: 107,
              type: 'IPAdapterApplyEncoded',
              pos: [-2639, -856],
              size: { '0': 315, '1': 214 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [
                { name: 'ipadapter', type: 'IPADAPTER', link: 228 },
                { name: 'embeds', type: 'EMBEDS', link: 247 },
                { name: 'model', type: 'MODEL', link: 231, slot_index: 2 },
                { name: 'attn_mask', type: 'MASK', link: null },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [232], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'IPAdapterApplyEncoded' },
              widgets_values: [0.8, 'original', 0, 1, false],
            },
            {
              id: 104,
              type: 'IPAdapterEncoder',
              pos: [-3289, -1111],
              size: { '0': 315, '1': 258 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'clip_vision', type: 'CLIP_VISION', link: 225, slot_index: 0 },
                { name: 'image_1', type: 'IMAGE', link: 233, slot_index: 1 },
                { name: 'image_2', type: 'IMAGE', link: null, slot_index: 2 },
                { name: 'image_3', type: 'IMAGE', link: null },
                { name: 'image_4', type: 'IMAGE', link: null },
              ],
              outputs: [{ name: 'EMBEDS', type: 'EMBEDS', links: [247], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'IPAdapterEncoder' },
              widgets_values: [true, 1, 1, 1, 1, 1],
            },
            {
              id: 116,
              type: 'SaveImage',
              pos: [-1805, 1636],
              size: [533.4844859730113, 507.5594371448865],
              flags: {},
              order: 25,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 246 }],
              properties: {},
              widgets_values: ['Eva'],
            },
            {
              id: 84,
              type: 'CLIPTextEncode',
              pos: [-2630, 434],
              size: [340.7228698730469, 100.44314575195312],
              flags: {},
              order: 21,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 187 },
                { name: 'text', type: 'STRING', link: 248, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [189],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 109,
              type: 'LoadImage',
              pos: [-3711, -1228],
              size: { '0': 315, '1': 314 },
              flags: {},
              order: 6,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [233], shape: 3 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [ipadapter_imgs[0].img, 'image'],
            },
            {
              id: 117,
              type: 'EmbeddingPicker',
              pos: [-3149, 377],
              size: { '0': 400, '1': 200 },
              flags: {},
              order: 7,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [248], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: ['EasyNegative.safetensors', 0.85, false, negative_prompt],
            },
          ],
          links: [
            [168, 71, 0, 70, 3, 'CONTROL_NET_STACK'],
            [170, 77, 0, 76, 0, 'IMAGE'],
            [172, 77, 0, 75, 0, 'IMAGE'],
            [174, 76, 0, 71, 1, 'IMAGE'],
            [175, 77, 0, 72, 0, 'IMAGE'],
            [176, 72, 0, 71, 2, 'IMAGE'],
            [180, 75, 0, 70, 2, 'IMAGE'],
            [185, 80, 1, 82, 1, 'CLIP'],
            [186, 82, 1, 83, 0, 'CLIP'],
            [187, 82, 1, 84, 0, 'CLIP'],
            [188, 83, 0, 79, 0, 'CONDITIONING'],
            [189, 84, 0, 79, 1, 'CONDITIONING'],
            [195, 79, 0, 89, 1, 'CONDITIONING'],
            [196, 82, 0, 90, 0, '*'],
            [197, 90, 0, 89, 0, 'MODEL'],
            [198, 79, 1, 89, 2, 'CONDITIONING'],
            [203, 89, 0, 94, 0, 'LATENT'],
            [204, 93, 0, 94, 1, 'VAE'],
            [211, 70, 0, 100, 3, 'CONTROL_NET_STACK'],
            [212, 100, 0, 79, 2, 'CONTROL_NET_STACK'],
            [216, 91, 0, 89, 3, 'LATENT'],
            [217, 80, 2, 91, 1, 'VAE'],
            [222, 72, 0, 91, 0, 'IMAGE'],
            [223, 81, 0, 103, 0, 'LORA_STACK'],
            [224, 103, 0, 82, 2, 'LORA_STACK'],
            [225, 105, 0, 104, 0, 'CLIP_VISION'],
            [228, 86, 0, 107, 0, 'IPADAPTER'],
            [231, 80, 0, 107, 2, 'MODEL'],
            [232, 107, 0, 82, 0, 'MODEL'],
            [233, 109, 0, 104, 1, 'IMAGE'],
            [246, 94, 0, 116, 0, 'IMAGE'],
            [247, 104, 0, 107, 1, 'EMBEDS'],
            [248, 117, 0, 84, 1, 'STRING'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
        },
      },
    },
  };
};
