export const arch_12_new = ({
  client_id,
  // 底图
  load_img,
  // 提示词
  text,
  // 底图相似度
  cn_strength,
  lora1_weight,
  lora1_clip,
  lora2_weight,
  lora2_clip,
  lora3_weight,
  lora3_clip,
  lora1_name,
  lora2_name,
  lora3_name,
  // 大模型
  ckpt,
}: any) => {
  const imgSize = 768;
  const sampler_name = 'euler_ancestral';
  const scheduler = 'simple';
  const steps = 15;
  const cfg = 7;
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = text.replaceAll('，', ',');
  console.log('arch_12_new', {
    client_id,
    load_img,
    text,
    cn_strength,
    input_seed,
    prompt,
    imgSize,
    sampler_name,
    scheduler,
    steps,
    cfg,
    lora1_weight,
    lora1_clip,
    lora2_weight,
    lora2_clip,
    ckpt,
    lora1_name,
    lora2_name,
  });
  return {
    client_id: '589fd366a8c44551b26f2dd230aa3872',
    prompt: {
      '1': {
        inputs: { image: '微信图片_20240224131610.jpg', upload: 'image' },
        class_type: 'LoadImage',
      },
      '4': { inputs: { text: ['69', 0], clip: ['59', 1] }, class_type: 'CLIPTextEncode' },
      '6': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: '真实感Photon_v1.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '7': { inputs: { text: ['8', 0], clip: ['59', 1] }, class_type: 'CLIPTextEncode' },
      '8': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '11': { inputs: { pixels: ['24', 0], vae: ['15', 0] }, class_type: 'VAEEncode' },
      '13': {
        inputs: {
          seed: 685282246998496,
          steps: 15,
          cfg: 7,
          sampler_name: 'euler_ancestral',
          scheduler: 'simple',
          denoise: 1,
          preview_method: 'none',
          vae_decode: 'true (tiled)',
          model: ['59', 0],
          positive: ['28', 0],
          negative: ['28', 1],
          latent_image: ['11', 0],
          optional_vae: ['15', 0],
          script: ['97', 0],
        },
        class_type: 'KSampler (Efficient)',
      },
      '14': { inputs: { samples: ['13', 3], vae: ['15', 0] }, class_type: 'VAEDecode' },
      '15': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '24': {
        inputs: { size: 768, mode: false, images: ['77', 0] },
        class_type: 'ImageScaleDownToSize',
      },
      '27': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_1: 0.6,
          start_percent_1: 0,
          end_percent_1: 0.8,
          switch_2: 'Off',
          controlnet_2: 'control_v11e_sd15_shuffle.pth',
          controlnet_strength_2: 0.5,
          start_percent_2: 0.5,
          end_percent_2: 1,
          switch_3: 'Off',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.3,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_1: ['29', 0],
          image_3: ['24', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '28': {
        inputs: {
          switch: 'On',
          base_positive: ['4', 0],
          base_negative: ['7', 0],
          controlnet_stack: ['27', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '29': {
        inputs: { coarse: 'disable', resolution: 768, image: ['24', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '49': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_BirdsView.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '50': {
        inputs: { ratio: 0.1, model1: ['49', 0], model2: ['6', 0] },
        class_type: 'ModelMergeSimple',
      },
      '58': {
        inputs: {
          switch_1: 'On',
          lora_name_1: '办公\\红砖建筑_v1.0.safetensors',
          model_weight_1: 0.5,
          clip_weight_1: 1,
          switch_2: 'On',
          lora_name_2: '景观\\现代庭院-冰醋酸_Modern Courtyard_现代庭院-冰醋酸1.0.safetensors',
          model_weight_2: 0.5,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: '建筑鸟瞰渲染风格_v1.0.safetensors',
          model_weight_3: 0.4,
          clip_weight_3: 0.8,
        },
        class_type: 'CR LoRA Stack',
      },
      '59': {
        inputs: { model: ['6', 0], clip: ['6', 1], lora_stack: ['58', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '69': { inputs: { Input: 1, text1: ['70', 0] }, class_type: 'CR Text Input Switch (4 way)' },
      '70': {
        inputs: {
          prompt:
            'school,playground,building, A high-definition image captures an aerial view of a modernist-style school with a beautiful and spacious playground. The lush green grass of the playground is complemented by facilities such as a basketball court or soccer field. The school buildings exhibit clean lines and a modern aesthetic,harmonizing with the surrounding urban landscape. Under the clear sky,the entire campus exudes tranquility and vitality,presenting an overall view of the school.blue sky and white cloud,Red brick facade',
        },
        class_type: 'CR Prompt Text',
      },
      '71': { inputs: { filename_prefix: 'ComfyUI', images: ['13', 5] }, class_type: 'SaveImage' },
      '76': {
        inputs: { model_name: '4x_foolhardy_Remacri.pth' },
        class_type: 'UpscaleModelLoader',
      },
      '77': {
        inputs: { upscale_method: 'nearest-exact', scale_by: 4, image: ['1', 0] },
        class_type: 'ImageScaleBy',
      },
      '97': {
        inputs: {
          grid_spacing: 0,
          XY_flip: 'False',
          Y_label_orientation: 'Horizontal',
          cache_models: 'True',
          ksampler_output_image: 'Images',
          X: ['98', 0],
        },
        class_type: 'XY Plot',
      },
      '98': { inputs: { batch_count: 2 }, class_type: 'XY Input: Seeds++ Batch' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 98,
          last_link_id: 248,
          nodes: [
            {
              id: 14,
              type: 'VAEDecode',
              pos: [-375.50544433593745, 968.4596984863282],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 27,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 139 },
                { name: 'vae', type: 'VAE', link: 96, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [-1246, 879],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 165 },
                { name: 'text', type: 'STRING', link: 195, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [63],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [-1242, 1004],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 166 },
                { name: 'text', type: 'STRING', link: 6, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [64],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 15,
              type: 'VAELoader',
              pos: [-752, 787],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [96, 97, 98], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 59,
              type: 'CR Apply LoRA Stack',
              pos: [-1935, 296],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 189 },
                { name: 'clip', type: 'CLIP', link: 186 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 161 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [164], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [165, 166], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 49,
              type: 'CheckpointLoader',
              pos: [-2333, 709],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [142], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_BirdsView.safetensors'],
            },
            {
              id: 50,
              type: 'ModelMergeSimple',
              pos: [-2321, 565],
              size: { '0': 315, '1': 78 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'model1', type: 'MODEL', link: 142 },
                { name: 'model2', type: 'MODEL', link: 143 },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ModelMergeSimple' },
              widgets_values: [0.1],
            },
            {
              id: 28,
              type: 'CR Apply Multi-ControlNet',
              pos: [-769, 617],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 25,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 63 },
                { name: 'base_negative', type: 'CONDITIONING', link: 64 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 62 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [196], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [137], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 29,
              type: 'LineArtPreprocessor',
              pos: [-1356, 184],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 67 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [200], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 66,
              type: 'AIO_Preprocessor',
              pos: [-956, 203],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 23,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 180 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'AIO_Preprocessor' },
              widgets_values: ['HEDPreprocessor', 768],
            },
            {
              id: 60,
              type: 'M-LSDPreprocessor',
              pos: [-1359, -69],
              size: { '0': 315, '1': 106 },
              flags: {},
              order: 22,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 167 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'M-LSDPreprocessor' },
              widgets_values: [0.1, 0.1, 768],
            },
            {
              id: 69,
              type: 'CR Text Input Switch (4 way)',
              pos: [-2677, 497],
              size: { '0': 315, '1': 174 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [
                { name: 'text1', type: 'STRING', link: 194, widget: { name: 'text1' } },
                { name: 'text2', type: 'STRING', link: null, widget: { name: 'text2' } },
                { name: 'text3', type: 'STRING', link: null, widget: { name: 'text3' } },
                { name: 'text4', type: 'STRING', link: null, widget: { name: 'text4' } },
              ],
              outputs: [
                { name: 'STRING', type: 'STRING', links: [195], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Text Input Switch (4 way)' },
              widgets_values: [1, '', '', '', ''],
            },
            {
              id: 8,
              type: 'EmbeddingPicker',
              pos: [-1571, 1005],
              size: { '0': 302.5414733886719, '1': 171.75250244140625 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [6], shape: 3 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
            {
              id: 17,
              type: 'CR Upscale Image',
              pos: [-1928, 885],
              size: { '0': 210, '1': 237.32579040527344 },
              flags: {},
              order: 18,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 206 }],
              outputs: [
                {
                  name: 'IMAGE',
                  type: 'IMAGE',
                  links: [27, 67, 71, 167, 180],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 76,
              type: 'UpscaleModelLoader',
              pos: [-1514, 1892],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [{ name: 'UPSCALE_MODEL', type: 'UPSCALE_MODEL', links: [212], shape: 3 }],
              properties: { 'Node name for S&R': 'UpscaleModelLoader' },
              widgets_values: ['4x_foolhardy_Remacri.pth'],
            },
            {
              id: 74,
              type: 'Image scale to side',
              pos: [-2770, 1188],
              size: { '0': 315, '1': 130 },
              flags: {},
              order: 9,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 204 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Image scale to side' },
              widgets_values: [1024, 'Longest', 'nearest-exact', 'disabled'],
            },
            {
              id: 77,
              type: 'ImageScaleBy',
              pos: [-2772, 905],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 214 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [215], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleBy' },
              widgets_values: ['nearest-exact', 4],
            },
            {
              id: 24,
              type: 'ImageScaleDownToSize',
              pos: [-2386, 896],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 215 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [206], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [768, false],
            },
            {
              id: 31,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1358, 83],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 21,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 71 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [108], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [768],
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [-2439, 1176],
              size: { '0': 363.5043029785156, '1': 365.5905456542969 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [204, 214], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: ['微信图片_20240224131610.jpg', 'image'],
            },
            {
              id: 70,
              type: 'CR Prompt Text',
              pos: [-2677, 258],
              size: { '0': 313.8494873046875, '1': 190.8131866455078 },
              flags: {},
              order: 5,
              mode: 0,
              inputs: [],
              outputs: [
                { name: 'prompt', type: 'STRING', links: [194], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Prompt Text' },
              widgets_values: [
                'school,playground,building, A high-definition image captures an aerial view of a modernist-style school with a beautiful and spacious playground. The lush green grass of the playground is complemented by facilities such as a basketball court or soccer field. The school buildings exhibit clean lines and a modern aesthetic,harmonizing with the surrounding urban landscape. Under the clear sky,the entire campus exudes tranquility and vitality,presenting an overall view of the school.blue sky and white cloud,Red brick facade',
              ],
            },
            {
              id: 27,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1440, 340],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 24,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 200 },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: 108 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [62],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_lineart.pth',
                0.6,
                0,
                0.8,
                'Off',
                'control_v11e_sd15_shuffle.pth',
                0.5,
                0.5,
                1,
                'Off',
                'control_v11p_sd15_depth.pth',
                0.3,
                0,
                0.6,
              ],
            },
            {
              id: 58,
              type: 'CR LoRA Stack',
              pos: [-2322, 161],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [161], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: [
                'On',
                '办公\\红砖建筑_v1.0.safetensors',
                0.5,
                1,
                'On',
                '景观\\现代庭院-冰醋酸_Modern Courtyard_现代庭院-冰醋酸1.0.safetensors',
                0.5,
                1,
                'Off',
                '建筑鸟瞰渲染风格_v1.0.safetensors',
                0.4,
                0.8,
              ],
            },
            {
              id: 6,
              type: 'CheckpointLoader',
              pos: [-1962, 711],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 7,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [143, 189], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [186], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', '真实感Photon_v1.safetensors'],
            },
            {
              id: 75,
              type: 'UltimateSDUpscale',
              pos: [-1569, 1225],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 28,
              mode: 4,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 207 },
                { name: 'model', type: 'MODEL', link: 208 },
                { name: 'positive', type: 'CONDITIONING', link: 209 },
                { name: 'negative', type: 'CONDITIONING', link: 210 },
                { name: 'vae', type: 'VAE', link: 211 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 212, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [238], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                2,
                82886087234233,
                'randomize',
                15,
                7,
                'euler_ancestral',
                'normal',
                0.1,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 11,
              type: 'VAEEncode',
              pos: [-1001, 888],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 27 },
                { name: 'vae', type: 'VAE', link: 98 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [247], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 97,
              type: 'XY Plot',
              pos: [-421, 1223],
              size: { '0': 315, '1': 194 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'dependencies', type: 'DEPENDENCIES', link: null },
                { name: 'X', type: 'XY', link: 248, slot_index: 1 },
                { name: 'Y', type: 'XY', link: null },
              ],
              outputs: [{ name: 'SCRIPT', type: 'SCRIPT', links: [245], shape: 3 }],
              properties: { 'Node name for S&R': 'XY Plot' },
              widgets_values: [0, 'False', 'Horizontal', 'True', 'Images'],
              color: '#332233',
              bgcolor: '#553355',
              shape: 1,
            },
            {
              id: 71,
              type: 'SaveImage',
              pos: [-2009, 1192],
              size: { '0': 350.8418273925781, '1': 393.9283142089844 },
              flags: {},
              order: 29,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 238 }],
              properties: {},
              widgets_values: ['ComfyUI'],
            },
            {
              id: 98,
              type: 'XY Input: Seeds++ Batch',
              pos: [-37, 1229],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 8,
              mode: 0,
              outputs: [{ name: 'X or Y', type: 'XY', links: [248], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'XY Input: Seeds++ Batch' },
              widgets_values: [2],
              color: '#223333',
              bgcolor: '#335555',
              shape: 1,
            },
            {
              id: 13,
              type: 'KSampler (Efficient)',
              pos: [-935, 1100],
              size: { '0': 325, '1': 562 },
              flags: {},
              order: 26,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 164 },
                { name: 'positive', type: 'CONDITIONING', link: 196 },
                { name: 'negative', type: 'CONDITIONING', link: 137 },
                { name: 'latent_image', type: 'LATENT', link: 247, slot_index: 3 },
                { name: 'optional_vae', type: 'VAE', link: 97 },
                { name: 'script', type: 'SCRIPT', link: 245, slot_index: 5 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [208], shape: 3, slot_index: 0 },
                {
                  name: 'CONDITIONING+',
                  type: 'CONDITIONING',
                  links: [209],
                  shape: 3,
                  slot_index: 1,
                },
                {
                  name: 'CONDITIONING-',
                  type: 'CONDITIONING',
                  links: [210],
                  shape: 3,
                  slot_index: 2,
                },
                { name: 'LATENT', type: 'LATENT', links: [139], shape: 3, slot_index: 3 },
                { name: 'VAE', type: 'VAE', links: [211], shape: 3, slot_index: 4 },
                { name: 'IMAGE', type: 'IMAGE', links: [207], shape: 3, slot_index: 5 },
              ],
              properties: { 'Node name for S&R': 'KSampler (Efficient)' },
              widgets_values: [
                -1,
                null,
                15,
                7,
                'euler_ancestral',
                'simple',
                1,
                'none',
                'true (tiled)',
              ],
              color: '#332233',
              bgcolor: '#553355',
              shape: 1,
            },
          ],
          links: [
            [6, 8, 0, 7, 1, 'STRING'],
            [27, 17, 0, 11, 0, 'IMAGE'],
            [62, 27, 0, 28, 2, 'CONTROL_NET_STACK'],
            [63, 4, 0, 28, 0, 'CONDITIONING'],
            [64, 7, 0, 28, 1, 'CONDITIONING'],
            [67, 17, 0, 29, 0, 'IMAGE'],
            [71, 17, 0, 31, 0, 'IMAGE'],
            [96, 15, 0, 14, 1, 'VAE'],
            [97, 15, 0, 13, 4, 'VAE'],
            [98, 15, 0, 11, 1, 'VAE'],
            [108, 31, 0, 27, 2, 'IMAGE'],
            [137, 28, 1, 13, 2, 'CONDITIONING'],
            [139, 13, 3, 14, 0, 'LATENT'],
            [142, 49, 0, 50, 0, 'MODEL'],
            [143, 6, 0, 50, 1, 'MODEL'],
            [161, 58, 0, 59, 2, 'LORA_STACK'],
            [164, 59, 0, 13, 0, 'MODEL'],
            [165, 59, 1, 4, 0, 'CLIP'],
            [166, 59, 1, 7, 0, 'CLIP'],
            [167, 17, 0, 60, 0, 'IMAGE'],
            [180, 17, 0, 66, 0, 'IMAGE'],
            [186, 6, 1, 59, 1, 'CLIP'],
            [189, 6, 0, 59, 0, 'MODEL'],
            [194, 70, 0, 69, 0, 'STRING'],
            [195, 69, 0, 4, 1, 'STRING'],
            [196, 28, 0, 13, 1, 'CONDITIONING'],
            [200, 29, 0, 27, 0, 'IMAGE'],
            [204, 1, 0, 74, 0, 'IMAGE'],
            [206, 24, 0, 17, 0, 'IMAGE'],
            [207, 13, 5, 75, 0, 'IMAGE'],
            [208, 13, 0, 75, 1, 'MODEL'],
            [209, 13, 1, 75, 2, 'CONDITIONING'],
            [210, 13, 2, 75, 3, 'CONDITIONING'],
            [211, 13, 4, 75, 4, 'VAE'],
            [212, 76, 0, 75, 5, 'UPSCALE_MODEL'],
            [214, 1, 0, 77, 0, 'IMAGE'],
            [215, 77, 0, 24, 0, 'IMAGE'],
            [238, 75, 0, 71, 0, 'IMAGE'],
            [245, 97, 0, 13, 5, 'SCRIPT'],
            [247, 11, 0, 13, 3, 'LATENT'],
            [248, 98, 0, 97, 1, 'XY'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: {
            '13': { seed: 0, sampler_name: 4, scheduler: 5 },
            '75': { seed: 1, sampler_name: 5, scheduler: 6 },
          },
        },
      },
    },
  };
};
