export const arch_12_new = ({
  client_id,
  // 底图
  load_img,
  // 提示词
  text,
  // 底图相似度
  cn_strength,
  lora1_weight,
  lora1_clip,
  lora2_weight,
  lora2_clip,
  lora3_weight,
  lora3_clip,
  lora1_name,
  lora2_name,
  lora3_name,
  // 大模型
  ckpt,
}: any) => {
  const imgSize = 768;
  const sampler_name = 'euler_ancestral';
  const scheduler = 'simple';
  const steps = 15;
  const cfg = 7;
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = text.replaceAll('，', ',');
  console.log('arch_12_new', {
    client_id,
    load_img,
    text,
    cn_strength,
    input_seed,
    prompt,
    imgSize,
    sampler_name,
    scheduler,
    steps,
    cfg,
    lora1_weight,
    lora1_clip,
    lora2_weight,
    lora2_clip,
    ckpt,
    lora1_name,
    lora2_name,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '4': { inputs: { text: ['48', 0], clip: ['54', 1] }, class_type: 'CLIPTextEncode' },
      '6': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: ckpt },
        class_type: 'CheckpointLoader',
      },
      '7': { inputs: { text: ['8', 0], clip: ['54', 1] }, class_type: 'CLIPTextEncode' },
      '8': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '11': { inputs: { pixels: ['24', 0], vae: ['15', 0] }, class_type: 'VAEEncode' },
      '14': { inputs: { samples: ['52', 0], vae: ['15', 0] }, class_type: 'VAEDecode' },
      '15': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '24': {
        inputs: { size: imgSize, mode: false, images: ['35', 0] },
        class_type: 'ImageScaleDownToSize',
      },
      '27': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_1: cn_strength,
          start_percent_1: 0,
          end_percent_1: 0.8,
          switch_2: 'Off',
          controlnet_2: 'control_v11e_sd15_shuffle.pth',
          controlnet_strength_2: 0.3,
          start_percent_2: 0,
          end_percent_2: 0.3,
          switch_3: 'Off',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.3,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_1: ['29', 0],
          image_2: ['24', 0],
          image_3: ['31', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '28': {
        inputs: {
          switch: 'On',
          base_positive: ['4', 0],
          base_negative: ['7', 0],
          controlnet_stack: ['27', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '29': {
        inputs: { coarse: 'disable', resolution: 768, image: ['24', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '31': {
        inputs: { resolution: 768, image: ['24', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '35': {
        inputs: { upscale_method: 'nearest-exact', scale_by: 4, image: ['1', 0] },
        class_type: 'ImageScaleBy',
      },
      '48': {
        inputs: {
          prompt: prompt,
        },
        class_type: 'CR Prompt Text',
      },
      '49': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_BirdsView.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '50': {
        inputs: { ratio: 0.1, model1: ['49', 0], model2: ['6', 0] },
        class_type: 'ModelMergeSimple',
      },
      '52': {
        inputs: {
          seed: input_seed,
          steps: steps,
          cfg: cfg,
          sampler_name: sampler_name,
          scheduler: scheduler,
          denoise: 1,
          preview_method: 'none',
          vae_decode: 'true (tiled)',
          model: ['54', 0],
          positive: ['28', 0],
          negative: ['28', 1],
          latent_image: ['11', 0],
          optional_vae: ['15', 0],
        },
        class_type: 'KSampler (Efficient)',
      },
      '53': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'Eva-GT.safetensors',
          model_weight_1: 0.3,
          clip_weight_1: 2,
          switch_2: lora1_name == 'None' ? 'Off' : 'On',
          lora_name_2: lora1_name,
          model_weight_2: lora1_weight,
          clip_weight_2: lora1_clip,
          switch_3: lora2_name == 'None' ? 'Off' : 'On',
          lora_name_3: lora2_name,
          model_weight_3: lora2_weight,
          clip_weight_3: lora2_clip,
        },
        class_type: 'CR LoRA Stack',
      },
      '54': {
        inputs: { model: ['50', 0], clip: ['6', 1], lora_stack: ['53', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '55': { inputs: { filename_prefix: 'EvaAI', images: ['14', 0] }, class_type: 'SaveImage' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 55,
          last_link_id: 169,
          nodes: [
            {
              id: 14,
              type: 'VAEDecode',
              pos: [-375.50544433593745, 968.4596984863282],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 161 },
                { name: 'vae', type: 'VAE', link: 96, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [169], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [-1246, 879],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 167 },
                { name: 'text', type: 'STRING', link: 141, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [63],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [-1242, 1004],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 168 },
                { name: 'text', type: 'STRING', link: 6, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [64],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 29,
              type: 'LineArtPreprocessor',
              pos: [-1356, 184],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 67 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [68], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 15,
              type: 'VAELoader',
              pos: [-752, 787],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [96, 98], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 31,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1358, 83],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 71 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [108], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [768],
            },
            {
              id: 8,
              type: 'EmbeddingPicker',
              pos: [-1586, 1131],
              size: { '0': 302.5414733886719, '1': 171.75250244140625 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [6], shape: 3 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
            {
              id: 28,
              type: 'CR Apply Multi-ControlNet',
              pos: [-769, 617],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 63 },
                { name: 'base_negative', type: 'CONDITIONING', link: 64 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 62 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [156], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [157], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 17,
              type: 'ImageScaleBy',
              pos: [1319, 585],
              size: { 0: 315, 1: 82 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 51 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [27, 67, 71, 122], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: ['nearest-exact', 4],
            },
            {
              id: 24,
              type: 'ImageScaleDownToSize',
              pos: [-2290, 907],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 85 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [51], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [imgSize, false],
            },
            {
              id: 35,
              type: 'CR Upscale Image',
              pos: [-2645, 901],
              size: { '0': 315, '1': 222 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 84 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [85], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 49,
              type: 'CheckpointLoader',
              pos: [-2333, 709],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [142], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_BirdsView.safetensors'],
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [-2326, 1153],
              size: { '0': 363.5043029785156, '1': 365.5905456542969 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [84], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 27,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1414, 349],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 68 },
                { name: 'image_2', type: 'IMAGE', link: 122 },
                { name: 'image_3', type: 'IMAGE', link: 108 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [62],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_lineart.pth',
                cn_strength,
                0,
                0.8,
                'Off',
                'control_v11e_sd15_shuffle.pth',
                0.3,
                0,
                0.3,
                'Off',
                'control_v11p_sd15_depth.pth',
                0.3,
                0,
                0.6,
              ],
            },
            {
              id: 48,
              type: 'CR Prompt Text',
              pos: [-1953, 443],
              size: { '0': 313.8494873046875, '1': 190.8131866455078 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'prompt', type: 'STRING', links: [141], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Prompt Text' },
              widgets_values: [prompt],
            },
            {
              id: 11,
              type: 'VAEEncode',
              pos: [-1001, 888],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 27 },
                { name: 'vae', type: 'VAE', link: 98 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [162], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 52,
              type: 'KSampler (Efficient)',
              pos: [-919, 1013],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 165 },
                { name: 'positive', type: 'CONDITIONING', link: 156 },
                { name: 'negative', type: 'CONDITIONING', link: 157 },
                { name: 'latent_image', type: 'LATENT', link: 162 },
                { name: 'optional_vae', type: 'VAE', link: 97 },
                { name: 'script', type: 'SCRIPT', link: null },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [208], shape: 3, slot_index: 0 },
                {
                  name: 'CONDITIONING+',
                  type: 'CONDITIONING',
                  links: [209],
                  shape: 3,
                  slot_index: 1,
                },
                {
                  name: 'CONDITIONING-',
                  type: 'CONDITIONING',
                  links: [210],
                  shape: 3,
                  slot_index: 2,
                },
                { name: 'LATENT', type: 'LATENT', links: [139], shape: 3, slot_index: 3 },
                { name: 'VAE', type: 'VAE', links: [211], shape: 3, slot_index: 4 },
                { name: 'IMAGE', type: 'IMAGE', links: [207], shape: 3, slot_index: 5 },
              ],
              properties: { 'Node name for S&R': 'KSampler (Efficient)' },
              widgets_values: [
                input_seed,
                null,
                steps,
                cfg,
                sampler_name,
                scheduler,
                1,
                'none',
                'true (tiled)',
              ],
              color: '#332233',
              bgcolor: '#553355',
              shape: 1,
            },
            {
              id: 50,
              type: 'ModelMergeSimple',
              pos: [-2320, 565],
              size: { '0': 315, '1': 78 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [
                { name: 'model1', type: 'MODEL', link: 142 },
                { name: 'model2', type: 'MODEL', link: 143 },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [164], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ModelMergeSimple' },
              widgets_values: [0.1],
            },
            {
              id: 6,
              type: 'CheckpointLoader',
              pos: [-1956, 704],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [143], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [166], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', ckpt],
            },
            {
              id: 54,
              type: 'CR Apply LoRA Stack',
              pos: [-1927, 318],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 164 },
                { name: 'clip', type: 'CLIP', link: 166 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 163 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [165], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [167, 168], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 53,
              type: 'CR LoRA Stack',
              pos: [-2318, 156],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [163], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: [
                'Off',
                'Eva-GT.safetensors',
                1,
                1,
                lora1_name == 'None' ? 'Off' : 'On',
                lora1_name,
                lora1_weight,
                lora1_clip,
                lora2_name == 'None' ? 'Off' : 'On',
                lora2_name,
                lora2_weight,
                lora2_clip,
              ],
            },
            {
              id: 55,
              type: 'SaveImage',
              pos: [-1938, 1177],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 21,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 169 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
          ],
          links: [
            [6, 8, 0, 7, 1, 'STRING'],
            [27, 17, 0, 11, 0, 'IMAGE'],
            [51, 24, 0, 17, 0, 'IMAGE'],
            [62, 27, 0, 28, 2, 'CONTROL_NET_STACK'],
            [63, 4, 0, 28, 0, 'CONDITIONING'],
            [64, 7, 0, 28, 1, 'CONDITIONING'],
            [67, 17, 0, 29, 0, 'IMAGE'],
            [68, 29, 0, 27, 0, 'IMAGE'],
            [71, 17, 0, 31, 0, 'IMAGE'],
            [84, 1, 0, 35, 0, 'IMAGE'],
            [85, 35, 0, 24, 0, 'IMAGE'],
            [96, 15, 0, 14, 1, 'VAE'],
            [98, 15, 0, 11, 1, 'VAE'],
            [108, 31, 0, 27, 2, 'IMAGE'],
            [122, 17, 0, 27, 1, 'IMAGE'],
            [141, 48, 0, 4, 1, 'STRING'],
            [142, 49, 0, 50, 0, 'MODEL'],
            [143, 6, 0, 50, 1, 'MODEL'],
            [156, 28, 0, 52, 1, 'CONDITIONING'],
            [157, 28, 1, 52, 2, 'CONDITIONING'],
            [161, 52, 0, 14, 0, 'LATENT'],
            [162, 11, 0, 52, 3, 'LATENT'],
            [163, 53, 0, 54, 2, 'LORA_STACK'],
            [164, 50, 0, 54, 0, 'MODEL'],
            [165, 54, 0, 52, 0, 'MODEL'],
            [166, 6, 1, 54, 1, 'CLIP'],
            [167, 54, 1, 4, 0, 'CLIP'],
            [168, 54, 1, 7, 0, 'CLIP'],
            [169, 14, 0, 55, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '52': { seed: 0, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
