export const birdsView = ({
  client_id,
  load_img,
  text,
  cn_strength,
  imgSize,
  sampler_name,
  scheduler,
  steps,
  cfg,
  lora1_weight,
  lora1_clip,
  lora2_weight,
  lora2_clip,
  ckpt,
  lora1_name,
  lora2_name,
}: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = text.replaceAll('，', ',');
  console.log({
    prompt,
    load_img,
    text,
  });
  return {
    client_id: client_id,
    prompt: {
      '70': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_canny.pth',
          controlnet_strength_1: 1,
          start_percent_1: 0,
          end_percent_1: 1,
          switch_2: 'Off',
          controlnet_2: 'control_v11p_sd15_soft.pth',
          controlnet_strength_2: 1,
          start_percent_2: 0,
          end_percent_2: 1,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.2,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_3: ['75', 0],
          controlnet_stack: ['71', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '71': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_mlsd.pth',
          controlnet_strength_1: 0.5,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'On',
          controlnet_2: 'control_v11p_sd15_seg.pth',
          controlnet_strength_2: 0.2,
          start_percent_2: 0,
          end_percent_2: 0.6,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_3: cn_strength.strength,
          start_percent_3: 0,
          end_percent_3: cn_strength.end,
          image_2: ['76', 0],
          image_3: ['72', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '72': {
        inputs: { coarse: 'disable', resolution: imgSize, image: ['77', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '75': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '76': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'OneFormer-COCO-SemSegPreprocessor',
      },
      '77': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '79': {
        inputs: {
          switch: 'On',
          base_positive: ['83', 0],
          base_negative: ['84', 0],
          controlnet_stack: ['100', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '80': {
        inputs: { ckpt_name: ckpt },
        class_type: 'CheckpointLoaderSimple',
      },
      '81': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'Eva-GT.safetensors',
          model_weight_1: 0.3,
          clip_weight_1: 2,
          switch_2: lora1_name == 'None' ? 'Off' : 'On',
          lora_name_2: lora1_name,
          model_weight_2: lora1_weight,
          clip_weight_2: lora1_clip,
          switch_3: lora2_name == 'None' ? 'Off' : 'On',
          lora_name_3: lora2_name,
          model_weight_3: lora2_weight,
          clip_weight_3: lora2_clip,
        },
        class_type: 'CR LoRA Stack',
      },
      '82': {
        inputs: { model: ['80', 0], clip: ['80', 1], lora_stack: ['103', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '83': {
        inputs: {
          text: prompt,
          clip: ['82', 1],
        },
        class_type: 'CLIPTextEncode',
      },
      '84': { inputs: { text: ['126', 0], clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
      '89': {
        inputs: {
          seed: input_seed,
          steps: steps,
          cfg: cfg,
          sampler_name: sampler_name,
          scheduler: scheduler,
          denoise: 1,
          model: ['82', 0],
          positive: ['79', 0],
          negative: ['79', 1],
          latent_image: ['91', 0],
        },
        class_type: 'KSampler',
      },
      '91': { inputs: { pixels: ['72', 0], vae: ['93', 0] }, class_type: 'VAEEncode' },
      '93': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '94': { inputs: { samples: ['89', 0], vae: ['93', 0] }, class_type: 'VAEDecode' },
      '100': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'None',
          controlnet_strength_1: 0.6,
          start_percent_1: 0,
          end_percent_1: 1,
          switch_2: 'Off',
          controlnet_2: 'None',
          controlnet_strength_2: 1,
          start_percent_2: 0,
          end_percent_2: 1,
          switch_3: 'Off',
          controlnet_3: 'None',
          controlnet_strength_3: 1,
          start_percent_3: 0,
          end_percent_3: 1,
          controlnet_stack: ['70', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '103': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 1,
          clip_weight_1: 1,
          switch_2: 'Off',
          lora_name_2: 'None',
          model_weight_2: 1,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 1,
          clip_weight_3: 1,
          lora_stack: ['81', 0],
        },
        class_type: 'CR LoRA Stack',
      },
      '126': {
        inputs: { embedding: 'EasyNegative.safetensors', emphasis: 1, append: false, text: '' },
        class_type: 'EmbeddingPicker',
      },
      '127': { inputs: { filename_prefix: 'EvaAI', images: ['94', 0] }, class_type: 'SaveImage' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 127,
          last_link_id: 269,
          nodes: [
            {
              id: 82,
              type: 'CR Apply LoRA Stack',
              pos: [-2616, 85],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 244 },
                { name: 'clip', type: 'CLIP', link: 185 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 224 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [196], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [186, 187], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 79,
              type: 'CR Apply Multi-ControlNet',
              pos: [-400, 743],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 188 },
                { name: 'base_negative', type: 'CONDITIONING', link: 189 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 212 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [195], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [198], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 103,
              type: 'CR LoRA Stack',
              pos: [-2301, -377],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 5,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: 223 }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [224], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: ['Off', 'None', 1, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
            },
            {
              id: 76,
              type: 'OneFormer-COCO-SemSegPreprocessor',
              pos: [-1970, 209],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 261 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [174], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'OneFormer-COCO-SemSegPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 75,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1431, 213],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 263 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [180], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 81,
              type: 'CR LoRA Stack',
              pos: [-2655, -375],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 0,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [223], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: [
                'Off',
                'Eva-GT.safetensors',
                1,
                1,
                lora1_name == 'None' ? 'Off' : 'On',
                lora1_name,
                lora1_weight,
                lora1_clip,
                lora2_name == 'None' ? 'Off' : 'On',
                lora2_name,
                lora2_weight,
                lora2_clip,
              ],
            },
            {
              id: 80,
              type: 'CheckpointLoaderSimple',
              pos: [-2657, -576],
              size: { '0': 315, '1': 98 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [244], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [185], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: [ckpt],
            },
            {
              id: 72,
              type: 'LineArtPreprocessor',
              pos: [-1684, 321],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 262 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [176, 265], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', imgSize],
            },
            {
              id: 89,
              type: 'KSampler',
              pos: [-1786, 1211],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 197 },
                { name: 'positive', type: 'CONDITIONING', link: 195 },
                { name: 'negative', type: 'CONDITIONING', link: 198 },
                { name: 'latent_image', type: 'LATENT', link: 266, slot_index: 3 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [203], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', steps, cfg, sampler_name, scheduler, 1],
            },
            {
              id: 100,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1030, 457],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null, slot_index: 0 },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: null },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 211, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [212],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'None',
                0.6,
                0,
                1,
                'Off',
                'None',
                1,
                0,
                1,
                'Off',
                'None',
                1,
                0,
                1,
              ],
            },
            {
              id: 93,
              type: 'VAELoader',
              pos: [-1879, 1009],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [204, 264], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 70,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1502, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: 180 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 168, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [211],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_canny.pth',
                1,
                0,
                1,
                'Off',
                'control_v11p_sd15_soft.pth',
                1,
                0,
                1,
                'On',
                'control_v11p_sd15_depth.pth',
                0.2,
                0,
                0.6,
              ],
            },
            {
              id: 77,
              type: 'LoadImage',
              pos: [-1230, 1502],
              size: [619.7150840720167, 677.9556866256216],
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [261, 262, 263], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 83,
              type: 'CLIPTextEncode',
              pos: [-2631, 233],
              size: { '0': 342.46282958984375, '1': 114.1131362915039 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [{ name: 'clip', type: 'CLIP', link: 186 }],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [188],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [prompt],
            },
            {
              id: 91,
              type: 'VAEEncode',
              pos: [-2062, 1279],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 265 },
                { name: 'vae', type: 'VAE', link: 264, slot_index: 1 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [266], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 90,
              type: 'Reroute',
              pos: [-2187, 942],
              size: [75, 26],
              flags: {},
              order: 12,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 196 }],
              outputs: [{ name: '', type: 'MODEL', links: [197], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 84,
              type: 'CLIPTextEncode',
              pos: [-2637, 425],
              size: [340.7228698730469, 100.44314575195312],
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 187 },
                { name: 'text', type: 'STRING', link: 268, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [189],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 126,
              type: 'EmbeddingPicker',
              pos: [-2653, 641],
              size: { '0': 400, '1': 200 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [268], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: ['EasyNegative.safetensors', 1, false, ''],
            },
            {
              id: 71,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1996, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: 174 },
                { name: 'image_3', type: 'IMAGE', link: 176 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null, slot_index: 3 },
              ],
              outputs: [
                { name: 'CONTROLNET_STACK', type: 'CONTROL_NET_STACK', links: [168], shape: 3 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_mlsd.pth',
                0.5,
                0,
                0.6,
                'On',
                'control_v11p_sd15_seg.pth',
                0.2,
                0,
                0.6,
                'On',
                'control_v11p_sd15_lineart.pth',
                cn_strength.strength,
                0,
                cn_strength.end,
              ],
            },
            {
              id: 94,
              type: 'VAEDecode',
              pos: [-1291, 1290],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 203 },
                { name: 'vae', type: 'VAE', link: 204, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [269], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 127,
              type: 'SaveImage',
              pos: [-1851, 1567],
              size: [555.7741015624995, 489.2480966796875],
              flags: {},
              order: 20,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 269 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
          ],
          links: [
            [168, 71, 0, 70, 3, 'CONTROL_NET_STACK'],
            [174, 76, 0, 71, 1, 'IMAGE'],
            [176, 72, 0, 71, 2, 'IMAGE'],
            [180, 75, 0, 70, 2, 'IMAGE'],
            [185, 80, 1, 82, 1, 'CLIP'],
            [186, 82, 1, 83, 0, 'CLIP'],
            [187, 82, 1, 84, 0, 'CLIP'],
            [188, 83, 0, 79, 0, 'CONDITIONING'],
            [189, 84, 0, 79, 1, 'CONDITIONING'],
            [195, 79, 0, 89, 1, 'CONDITIONING'],
            [196, 82, 0, 90, 0, '*'],
            [197, 90, 0, 89, 0, 'MODEL'],
            [198, 79, 1, 89, 2, 'CONDITIONING'],
            [203, 89, 0, 94, 0, 'LATENT'],
            [204, 93, 0, 94, 1, 'VAE'],
            [211, 70, 0, 100, 3, 'CONTROL_NET_STACK'],
            [212, 100, 0, 79, 2, 'CONTROL_NET_STACK'],
            [223, 81, 0, 103, 0, 'LORA_STACK'],
            [224, 103, 0, 82, 2, 'LORA_STACK'],
            [244, 80, 0, 82, 0, 'MODEL'],
            [261, 77, 0, 76, 0, 'IMAGE'],
            [262, 77, 0, 72, 0, 'IMAGE'],
            [263, 77, 0, 75, 0, 'IMAGE'],
            [264, 93, 0, 91, 1, 'VAE'],
            [265, 72, 0, 91, 0, 'IMAGE'],
            [266, 91, 0, 89, 3, 'LATENT'],
            [268, 126, 0, 84, 1, 'STRING'],
            [269, 94, 0, 127, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '89': { seed: 0, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
