export const buildingExteriorByImg = ({ client_id, mask_img, img, text, contronet }: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  console.log({
    client_id,
    mask_img,
    img,
    text,
    contronet,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
      '2': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '3': {
        inputs: { ipadapter_file: 'ip_adapter-plus.bin' },
        class_type: 'IPAdapterModelLoader',
      },
      '4': { inputs: { clip_name: 'SD1.5\\pytorch_model.bin' }, class_type: 'CLIPVisionLoader' },
      '7': {
        inputs: {
          text: text,
          clip: ['32', 1],
        },
        class_type: 'CLIPTextEncode',
      },
      '8': { inputs: { text: ['17', 0], clip: ['32', 1] }, class_type: 'CLIPTextEncode' },
      '9': {
        inputs: {
          seed: input_seed,
          steps: 15,
          cfg: 5,
          sampler_name: 'dpmpp_3m_sde',
          scheduler: 'karras',
          denoise: 1,
          model: ['16', 0],
          positive: ['28', 0],
          negative: ['28', 1],
          latent_image: ['21', 0],
        },
        class_type: 'KSampler',
      },
      '11': { inputs: { samples: ['9', 0], vae: ['2', 0] }, class_type: 'VAEDecode' },
      '12': {
        inputs: { filename_prefix: 'IPAdapter', images: ['11', 0] },
        class_type: 'SaveImage',
      },
      '15': {
        inputs: { image: img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '16': {
        inputs: {
          weight: 1,
          noise: 0,
          weight_type: 'original',
          start_at: 0,
          end_at: 1,
          unfold_batch: false,
          ipadapter: ['3', 0],
          clip_vision: ['4', 0],
          image: ['15', 0],
          model: ['32', 0],
        },
        class_type: 'IPAdapterApply',
      },
      '17': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '18': {
        inputs: { image: `${mask_img} [input]`, upload: 'image' },
        class_type: 'LoadImage',
      },
      '19': { inputs: { pixels: ['29', 0], vae: ['2', 0] }, class_type: 'VAEEncode' },
      '21': { inputs: { samples: ['19', 0], mask: ['22', 0] }, class_type: 'SetLatentNoiseMask' },
      '22': { inputs: { mask: ['18', 1] }, class_type: 'InvertMask' },
      '24': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_depth.pth',
          controlnet_strength_1: 0.3,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'On',
          controlnet_2: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_2: contronet / 100,
          start_percent_2: 0,
          end_percent_2: contronet / 100,
          switch_3: 'Off',
          controlnet_3: 'None',
          controlnet_strength_3: 1,
          start_percent_3: 0,
          end_percent_3: 1,
          image_1: ['26', 0],
          image_2: ['27', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '26': {
        inputs: { resolution: 768, image: ['18', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '27': {
        inputs: { coarse: 'disable', resolution: 768, image: ['18', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '28': {
        inputs: {
          switch: 'On',
          base_positive: ['7', 0],
          base_negative: ['8', 0],
          controlnet_stack: ['24', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '29': {
        inputs: { size: 768, mode: false, images: ['18', 0] },
        class_type: 'ImageScaleDownToSize',
      },
      '30': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 1,
          clip_weight_1: 1,
          switch_2: 'Off',
          lora_name_2: 'None',
          model_weight_2: 1,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 1,
          clip_weight_3: 1,
        },
        class_type: 'CR LoRA Stack',
      },
      '32': {
        inputs: { model: ['1', 0], clip: ['1', 1], lora_stack: ['30', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 32,
          last_link_id: 61,
          nodes: [
            {
              id: 11,
              type: 'VAEDecode',
              pos: [1470, 120],
              size: { '0': 140, '1': 50 },
              flags: {},
              order: 21,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 11 },
                { name: 'vae', type: 'VAE', link: 12 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [13], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 16,
              type: 'IPAdapterApply',
              pos: [943, -391],
              size: { '0': 315, '1': 258 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [
                { name: 'ipadapter', type: 'IPADAPTER', link: 23 },
                { name: 'clip_vision', type: 'CLIP_VISION', link: 24 },
                { name: 'image', type: 'IMAGE', link: 25 },
                { name: 'model', type: 'MODEL', link: 58 },
                { name: 'attn_mask', type: 'MASK', link: null },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [27], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'IPAdapterApply' },
              widgets_values: [1, 0, 'original', 0, 1, false],
            },
            {
              id: 17,
              type: 'EmbeddingPicker',
              pos: [544, 391],
              size: [219.94407135009703, 148.0000057220459],
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [28], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
            {
              id: 2,
              type: 'VAELoader',
              pos: [1110, 460],
              size: { '0': 300, '1': 60 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [12, 30], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 19,
              type: 'VAEEncode',
              pos: [576, 613],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 48 },
                { name: 'vae', type: 'VAE', link: 30 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [32], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 21,
              type: 'SetLatentNoiseMask',
              pos: [827, 616],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 32 },
                { name: 'mask', type: 'MASK', link: 35 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [33], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'SetLatentNoiseMask' },
            },
            {
              id: 15,
              type: 'LoadImage',
              pos: [424, -175],
              size: { '0': 220, '1': 320 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [25], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [img, 'image'],
            },
            {
              id: 22,
              type: 'InvertMask',
              pos: [569, 718],
              size: [214.28847106933608, 26],
              flags: {},
              order: 11,
              mode: 0,
              inputs: [{ name: 'mask', type: 'MASK', link: 34 }],
              outputs: [{ name: 'MASK', type: 'MASK', links: [35], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'InvertMask' },
            },
            {
              id: 26,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [1426, -570],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 38 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [39], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [768],
            },
            {
              id: 27,
              type: 'LineArtPreprocessor',
              pos: [1422, -702],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 40 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [41], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 8,
              type: 'CLIPTextEncode',
              pos: [820, 350],
              size: [210, 120],
              flags: {},
              order: 17,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 61 },
                { name: 'text', type: 'STRING', link: 28, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [44],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: ['blurry, horror'],
              color: '#322',
              bgcolor: '#533',
            },
            {
              id: 28,
              type: 'CR Apply Multi-ControlNet',
              pos: [1852, -364],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 43 },
                { name: 'base_negative', type: 'CONDITIONING', link: 44 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 42 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [45], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [46], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 18,
              type: 'LoadImage',
              pos: [270, 418],
              size: { '0': 220, '1': 320 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [38, 40, 47], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: [34], shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [`${mask_img} [input]`, 'image'],
            },
            {
              id: 29,
              type: 'ImageScaleDownToSize',
              pos: [575, 796],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 47 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [48], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [768, false],
            },
            {
              id: 12,
              type: 'SaveImage',
              pos: [1473, 232],
              size: { '0': 400, '1': 450 },
              flags: {},
              order: 22,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 13 }],
              properties: {},
              widgets_values: ['IPAdapter'],
            },
            {
              id: 3,
              type: 'IPAdapterModelLoader',
              pos: [426, -408],
              size: { '0': 260, '1': 60 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'IPADAPTER', type: 'IPADAPTER', links: [23], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'IPAdapterModelLoader' },
              widgets_values: ['ip_adapter-plus.bin'],
            },
            {
              id: 4,
              type: 'CLIPVisionLoader',
              pos: [428, -294],
              size: { '0': 300, '1': 60 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'CLIP_VISION', type: 'CLIP_VISION', links: [24], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'CLIPVisionLoader' },
              widgets_values: ['SD1.5\\pytorch_model.bin'],
            },
            {
              id: 9,
              type: 'KSampler',
              pos: [1100, 150],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 27 },
                { name: 'positive', type: 'CONDITIONING', link: 45 },
                { name: 'negative', type: 'CONDITIONING', link: 46 },
                { name: 'latent_image', type: 'LATENT', link: 33 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [11], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', 15, 5, 'dpmpp_3m_sde', 'karras', 1],
            },
            {
              id: 24,
              type: 'CR Multi-ControlNet Stack',
              pos: [1380, -430],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 39 },
                { name: 'image_2', type: 'IMAGE', link: 41 },
                { name: 'image_3', type: 'IMAGE', link: null },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [42],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_depth.pth',
                0.3,
                0,
                0.6,
                'On',
                'control_v11p_sd15_lineart.pth',
                contronet / 100,
                0,
                contronet / 100,
                'Off',
                'None',
                1,
                0,
                1,
              ],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [820, 180],
              size: { '0': 210, '1': 120 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [{ name: 'clip', type: 'CLIP', link: 60 }],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [43],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [text],
              color: '#232',
              bgcolor: '#353',
            },
            {
              id: 30,
              type: 'CR LoRA Stack',
              pos: [1097, 607],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [56], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: ['Off', 'None', 1, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
            },
            {
              id: 1,
              type: 'CheckpointLoaderSimple',
              pos: [347, 229],
              size: { '0': 300, '1': 100 },
              flags: {},
              order: 7,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [57], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [59], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: ['Eva_AI.safetensors'],
            },
            {
              id: 32,
              type: 'CR Apply LoRA Stack',
              pos: [800, 26],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 57 },
                { name: 'clip', type: 'CLIP', link: 59, slot_index: 1 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 56 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [58], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [60, 61], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
          ],
          links: [
            [11, 9, 0, 11, 0, 'LATENT'],
            [12, 2, 0, 11, 1, 'VAE'],
            [13, 11, 0, 12, 0, 'IMAGE'],
            [23, 3, 0, 16, 0, 'IPADAPTER'],
            [24, 4, 0, 16, 1, 'CLIP_VISION'],
            [25, 15, 0, 16, 2, 'IMAGE'],
            [27, 16, 0, 9, 0, 'MODEL'],
            [28, 17, 0, 8, 1, 'STRING'],
            [30, 2, 0, 19, 1, 'VAE'],
            [32, 19, 0, 21, 0, 'LATENT'],
            [33, 21, 0, 9, 3, 'LATENT'],
            [34, 18, 1, 22, 0, 'MASK'],
            [35, 22, 0, 21, 1, 'MASK'],
            [38, 18, 0, 26, 0, 'IMAGE'],
            [39, 26, 0, 24, 0, 'IMAGE'],
            [40, 18, 0, 27, 0, 'IMAGE'],
            [41, 27, 0, 24, 1, 'IMAGE'],
            [42, 24, 0, 28, 2, 'CONTROL_NET_STACK'],
            [43, 7, 0, 28, 0, 'CONDITIONING'],
            [44, 8, 0, 28, 1, 'CONDITIONING'],
            [45, 28, 0, 9, 1, 'CONDITIONING'],
            [46, 28, 1, 9, 2, 'CONDITIONING'],
            [47, 18, 0, 29, 0, 'IMAGE'],
            [48, 29, 0, 19, 0, 'IMAGE'],
            [56, 30, 0, 32, 2, 'LORA_STACK'],
            [57, 1, 0, 32, 0, 'MODEL'],
            [58, 32, 0, 16, 3, 'MODEL'],
            [59, 1, 1, 32, 1, 'CLIP'],
            [60, 32, 1, 7, 0, 'CLIP'],
            [61, 32, 1, 8, 0, 'CLIP'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '9': { seed: 0, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
