export const buildingExteriorByPrompt = ({ client_id, mask_img, text, contronet }: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  console.log({
    client_id,
    mask_img,
    text,
    contronet,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': {
        inputs: {
          image: `${mask_img} [input]`,
          upload: 'image',
        },
        class_type: 'LoadImage',
      },
      '4': { inputs: { text: ['48', 0], clip: ['60', 1] }, class_type: 'CLIPTextEncode' },
      '6': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_AI.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '7': { inputs: { text: ['8', 0], clip: ['60', 1] }, class_type: 'CLIPTextEncode' },
      '8': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '11': { inputs: { pixels: ['24', 0], vae: ['15', 0] }, class_type: 'VAEEncode' },
      '14': { inputs: { samples: ['62', 0], vae: ['15', 0] }, class_type: 'VAEDecode' },
      '15': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '24': {
        inputs: { size: 768, mode: false, images: ['35', 0] },
        class_type: 'ImageScaleDownToSize',
      },
      '27': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_1: contronet / 100,
          start_percent_1: 0,
          end_percent_1: contronet / 100,
          switch_2: 'Off',
          controlnet_2: 'control_v11e_sd15_shuffle.pth',
          controlnet_strength_2: 0.3,
          start_percent_2: 0,
          end_percent_2: 0.3,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.3,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_1: ['29', 0],
          image_2: ['24', 0],
          image_3: ['31', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '28': {
        inputs: {
          switch: 'On',
          base_positive: ['4', 0],
          base_negative: ['7', 0],
          controlnet_stack: ['27', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '29': {
        inputs: { coarse: 'disable', resolution: 768, image: ['24', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '31': {
        inputs: { resolution: 768, image: ['24', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '35': {
        inputs: {
          upscale_model: '4x_foolhardy_Remacri.pth',
          mode: 'rescale',
          rescale_factor: 1.5,
          resize_width: 1024,
          resampling_method: 'lanczos',
          supersample: 'true',
          rounding_modulus: 8,
          image: ['1', 0],
        },
        class_type: 'CR Upscale Image',
      },
      '48': {
        inputs: {
          prompt: text,
        },
        class_type: 'CR Prompt Text',
      },
      '49': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_BirdsView.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '50': {
        inputs: { ratio: 0, model1: ['49', 0], model2: ['6', 0] },
        class_type: 'ModelMergeSimple',
      },
      '53': { inputs: { samples: ['11', 0], mask: ['54', 0] }, class_type: 'SetLatentNoiseMask' },
      '54': { inputs: { mask: ['1', 1] }, class_type: 'InvertMask' },
      '59': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 1,
          clip_weight_1: 1,
          switch_2: 'Off',
          lora_name_2: 'None',
          model_weight_2: 1,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 1,
          clip_weight_3: 1,
        },
        class_type: 'CR LoRA Stack',
      },
      '60': {
        inputs: { model: ['50', 0], clip: ['6', 1], lora_stack: ['59', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '61': { inputs: { filename_prefix: 'EvaAI', images: ['14', 0] }, class_type: 'SaveImage' },
      '62': {
        inputs: {
          seed: input_seed,
          steps: 15,
          cfg: 5,
          sampler_name: 'dpmpp_3m_sde',
          scheduler: 'karras',
          denoise: 1,
          model: ['60', 0],
          positive: ['28', 0],
          negative: ['28', 1],
          latent_image: ['53', 0],
        },
        class_type: 'KSampler',
      },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 62,
          last_link_id: 178,
          nodes: [
            {
              id: 14,
              type: 'VAEDecode',
              pos: [-375.50544433593745, 968.4596984863282],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 22,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 178 },
                { name: 'vae', type: 'VAE', link: 96, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [173], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [-1246, 879],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 171 },
                { name: 'text', type: 'STRING', link: 141, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [63],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [-1242, 1004],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 172 },
                { name: 'text', type: 'STRING', link: 6, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [64],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 29,
              type: 'LineArtPreprocessor',
              pos: [-1356, 184],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 67 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [68], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 15,
              type: 'VAELoader',
              pos: [-752, 787],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [96, 98], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 31,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1358, 83],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 71 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [108], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [768],
            },
            {
              id: 49,
              type: 'CheckpointLoader',
              pos: [-2333, 709],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [142], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_BirdsView.safetensors'],
            },
            {
              id: 11,
              type: 'VAEEncode',
              pos: [-1001, 888],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 27 },
                { name: 'vae', type: 'VAE', link: 98 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [155], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 54,
              type: 'InvertMask',
              pos: [-1240, 1234],
              size: { '0': 210, '1': 26 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [{ name: 'mask', type: 'MASK', link: 158 }],
              outputs: [{ name: 'MASK', type: 'MASK', links: [159], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'InvertMask' },
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [-2695, 1153],
              size: { '0': 363.5043029785156, '1': 365.5905456542969 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [84], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: [158], shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [`${mask_img} [input]`, 'image'],
            },
            {
              id: 27,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1412, 329],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 68 },
                { name: 'image_2', type: 'IMAGE', link: 122 },
                { name: 'image_3', type: 'IMAGE', link: 108 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [62],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_lineart.pth',
                contronet / 100,
                0,
                contronet / 100,
                'Off',
                'control_v11e_sd15_shuffle.pth',
                0.3,
                0,
                0.3,
                'On',
                'control_v11p_sd15_depth.pth',
                0.3,
                0,
                0.6,
              ],
            },
            {
              id: 35,
              type: 'CR Upscale Image',
              pos: [-2662, 885],
              size: { '0': 315, '1': 222 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 84 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [85], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 48,
              type: 'CR Prompt Text',
              pos: [-1953, 443],
              size: [359.1498535156252, 175.93026550292973],
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'prompt', type: 'STRING', links: [141], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Prompt Text' },
              widgets_values: [text],
            },
            {
              id: 24,
              type: 'ImageScaleDownToSize',
              pos: [-2317, 891],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 85 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [51], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [768, false],
            },
            {
              id: 17,
              type: 'CR Upscale Image',
              pos: [-1956, 894],
              size: { '0': 315, '1': 222 },
              flags: {},
              order: 12,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 51 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [27, 67, 71, 122], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 8,
              type: 'EmbeddingPicker',
              pos: [-1230, 1320],
              size: { '0': 302.5414733886719, '1': 171.75250244140625 },
              flags: { collapsed: true },
              order: 4,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [6], shape: 3 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
            {
              id: 59,
              type: 'CR LoRA Stack',
              pos: [-1592, 884],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 5,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [167], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: ['Off', 'None', 1, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
            },
            {
              id: 50,
              type: 'ModelMergeSimple',
              pos: [-2321, 565],
              size: { '0': 315, '1': 78 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [
                { name: 'model1', type: 'MODEL', link: 142 },
                { name: 'model2', type: 'MODEL', link: 143 },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [168], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ModelMergeSimple' },
              widgets_values: [0],
            },
            {
              id: 6,
              type: 'CheckpointLoader',
              pos: [-1964, 710],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 6,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [143], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [169], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_AI.safetensors'],
            },
            {
              id: 60,
              type: 'CR Apply LoRA Stack',
              pos: [-1569, 1283],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 168 },
                { name: 'clip', type: 'CLIP', link: 169 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 167 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [174], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [171, 172], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 61,
              type: 'SaveImage',
              pos: [-2008, 1188],
              size: [384.03879492187525, 319.6686577148439],
              flags: {},
              order: 23,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 173 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
            {
              id: 28,
              type: 'CR Apply Multi-ControlNet',
              pos: [-769, 617],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 63 },
                { name: 'base_negative', type: 'CONDITIONING', link: 64 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 62 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [175], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [176], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 53,
              type: 'SetLatentNoiseMask',
              pos: [-1244, 1139],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 155 },
                { name: 'mask', type: 'MASK', link: 159 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [177], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'SetLatentNoiseMask' },
            },
            {
              id: 62,
              type: 'KSampler',
              pos: [-992, 1000],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 21,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 174 },
                { name: 'positive', type: 'CONDITIONING', link: 175 },
                { name: 'negative', type: 'CONDITIONING', link: 176 },
                { name: 'latent_image', type: 'LATENT', link: 177 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [178], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [0, 'randomize', 15, 5, 'dpmpp_3m_sde', 'karras', 1],
            },
          ],
          links: [
            [6, 8, 0, 7, 1, 'STRING'],
            [27, 17, 0, 11, 0, 'IMAGE'],
            [51, 24, 0, 17, 0, 'IMAGE'],
            [62, 27, 0, 28, 2, 'CONTROL_NET_STACK'],
            [63, 4, 0, 28, 0, 'CONDITIONING'],
            [64, 7, 0, 28, 1, 'CONDITIONING'],
            [67, 17, 0, 29, 0, 'IMAGE'],
            [68, 29, 0, 27, 0, 'IMAGE'],
            [71, 17, 0, 31, 0, 'IMAGE'],
            [84, 1, 0, 35, 0, 'IMAGE'],
            [85, 35, 0, 24, 0, 'IMAGE'],
            [96, 15, 0, 14, 1, 'VAE'],
            [98, 15, 0, 11, 1, 'VAE'],
            [108, 31, 0, 27, 2, 'IMAGE'],
            [122, 17, 0, 27, 1, 'IMAGE'],
            [141, 48, 0, 4, 1, 'STRING'],
            [142, 49, 0, 50, 0, 'MODEL'],
            [143, 6, 0, 50, 1, 'MODEL'],
            [155, 11, 0, 53, 0, 'LATENT'],
            [158, 1, 1, 54, 0, 'MASK'],
            [159, 54, 0, 53, 1, 'MASK'],
            [167, 59, 0, 60, 2, 'LORA_STACK'],
            [168, 50, 0, 60, 0, 'MODEL'],
            [169, 6, 1, 60, 1, 'CLIP'],
            [171, 60, 1, 4, 0, 'CLIP'],
            [172, 60, 1, 7, 0, 'CLIP'],
            [173, 14, 0, 61, 0, 'IMAGE'],
            [174, 60, 0, 62, 0, 'MODEL'],
            [175, 28, 0, 62, 1, 'CONDITIONING'],
            [176, 28, 1, 62, 2, 'CONDITIONING'],
            [177, 53, 0, 62, 3, 'LATENT'],
            [178, 62, 0, 14, 0, 'LATENT'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '62': { seed: input_seed, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
