export const colorFlatPicture = ({
  client_id,
  load_img,
  text,
  lora_name,
  lora_weight,
  lora_clip,
}: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = text.replaceAll('，', ',');
  prompt = `Rendering floor plan of the apartment layout,top view,(masterpiece),(best quality),Details,${prompt}`;
  console.log({
    prompt,
    load_img,
    text,
    lora_name,
    lora_weight,
    lora_clip,
  });
  return {
    client_id: client_id,
    prompt: {
      '71': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_depth.pth',
          controlnet_strength_1: 0.6,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'Off',
          controlnet_2: 'control_v11p_sd15_seg.pth',
          controlnet_strength_2: 0.15,
          start_percent_2: 0.049,
          end_percent_2: 0.6,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_3: 1,
          start_percent_3: 0,
          end_percent_3: 1,
          image_1: ['158', 0],
          image_3: ['72', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '72': {
        inputs: { coarse: 'disable', resolution: 768, image: ['77', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '77': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '79': {
        inputs: {
          switch: 'On',
          base_positive: ['83', 0],
          base_negative: ['84', 0],
          controlnet_stack: ['71', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '80': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
      '83': {
        inputs: {
          text: prompt,
          clip: ['160', 1],
        },
        class_type: 'CLIPTextEncode',
      },
      '84': { inputs: { text: ['145', 0], clip: ['160', 1] }, class_type: 'CLIPTextEncode' },
      '91': { inputs: { pixels: ['72', 0], vae: ['80', 2] }, class_type: 'VAEEncode' },
      '93': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '94': { inputs: { samples: ['157', 0], vae: ['93', 0] }, class_type: 'VAEDecode' },
      '145': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.75,
          append: true,
          text: 'bad',
        },
        class_type: 'EmbeddingPicker',
      },
      '148': { inputs: { filename_prefix: 'Eva', images: ['94', 0] }, class_type: 'SaveImage' },
      '157': {
        inputs: {
          seed: input_seed,
          steps: 15,
          cfg: 8,
          sampler_name: 'euler',
          scheduler: 'normal',
          denoise: 1,
          model: ['160', 0],
          positive: ['79', 0],
          negative: ['79', 1],
          latent_image: ['91', 0],
        },
        class_type: 'KSampler',
      },
      '158': {
        inputs: { a: 6.283185307179586, bg_threshold: 0.1, resolution: 512, image: ['77', 0] },
        class_type: 'MiDaS-DepthMapPreprocessor',
      },
      '160': {
        inputs: {
          switch: lora_name ? 'On' : 'Off',
          lora_name: lora_name || 'Eva-GT.safetensors',
          strength_model: lora_weight,
          strength_clip: lora_clip,
          model: ['80', 0],
          clip: ['80', 1],
        },
        class_type: 'CR Load LoRA',
      },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 160,
          last_link_id: 336,
          nodes: [
            {
              id: 84,
              type: 'CLIPTextEncode',
              pos: [-2628, 460],
              size: { '0': 340.7228698730469, '1': 100.44314575195312 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 336 },
                { name: 'text', type: 'STRING', link: 287, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [189],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 94,
              type: 'VAEDecode',
              pos: [-1402, 1240],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 325 },
                { name: 'vae', type: 'VAE', link: 204, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [309], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 72,
              type: 'LineArtPreprocessor',
              pos: [-1696, 321],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 4,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 175 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [176, 278], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 93,
              type: 'VAELoader',
              pos: [-1896, 957],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [204], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 90,
              type: 'Reroute',
              pos: [-2582, 893],
              size: [75, 26],
              flags: {},
              order: 9,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 334 }],
              outputs: [{ name: '', type: 'MODEL', links: [321], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 117,
              type: 'Reroute',
              pos: [-2581, 967],
              size: [75, 26],
              flags: {},
              order: 13,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 245 }],
              outputs: [{ name: '', type: 'CONDITIONING', links: [322], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 118,
              type: 'Reroute',
              pos: [-2580, 1022],
              size: [75, 26],
              flags: {},
              order: 14,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 246 }],
              outputs: [{ name: '', type: 'CONDITIONING', links: [323], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 91,
              type: 'VAEEncode',
              pos: [-2249, 1247],
              size: { '0': 210.693603515625, '1': 65.94579315185547 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 278 },
                { name: 'vae', type: 'VAE', link: 217, slot_index: 1 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [324], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 157,
              type: 'KSampler',
              pos: [-1898, 1091],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 321 },
                { name: 'positive', type: 'CONDITIONING', link: 322 },
                { name: 'negative', type: 'CONDITIONING', link: 323 },
                { name: 'latent_image', type: 'LATENT', link: 324 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [325], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', 20, 8, 'euler', 'normal', 1],
            },
            {
              id: 83,
              type: 'CLIPTextEncode',
              pos: [-2627, 277],
              size: { '0': 342.46282958984375, '1': 114.1131362915039 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'clip', type: 'CLIP', link: 335 }],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [188],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [prompt],
            },
            {
              id: 158,
              type: 'MiDaS-DepthMapPreprocessor',
              pos: [-1913, 171],
              size: { '0': 315, '1': 106 },
              flags: {},
              order: 5,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 326 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [327], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'MiDaS-DepthMapPreprocessor' },
              widgets_values: [6.283185307179586, 0.1, 512],
            },
            {
              id: 79,
              type: 'CR Apply Multi-ControlNet',
              pos: [-1455, 623],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 188 },
                { name: 'base_negative', type: 'CONDITIONING', link: 189 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 328 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [245], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [246], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 71,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1991, 458],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 327 },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: 176 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [328],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_depth.pth',
                0.6,
                0,
                0.1,
                'Off',
                'control_v11p_sd15_seg.pth',
                0.15,
                0.049,
                0.6,
                'On',
                'control_v11p_sd15_lineart.pth',
                1,
                0,
                1,
              ],
            },
            {
              id: 145,
              type: 'EmbeddingPicker',
              pos: [-3138, 476],
              size: { '0': 400, '1': 200 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [287], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: ['EasyNegative.safetensors', 0.75, true, 'bad'],
            },
            {
              id: 148,
              type: 'SaveImage',
              pos: [-2023, 1472],
              size: { '0': 616.0947265625, '1': 654.5961303710938 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 309 }],
              properties: {},
              widgets_values: ['Eva'],
            },
            {
              id: 77,
              type: 'LoadImage',
              pos: [-1390, 1451],
              size: { '0': 612.6759033203125, '1': 692.9805297851562 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [175, 326], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 80,
              type: 'CheckpointLoaderSimple',
              pos: [-2682, -245],
              size: { '0': 315, '1': 98 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [332], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [333], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [217], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: ['Eva_AI.safetensors'],
            },
            {
              id: 160,
              type: 'CR Load LoRA',
              pos: [-2618, -6],
              size: { '0': 315, '1': 170 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 332 },
                { name: 'clip', type: 'CLIP', link: 333 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [334], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [335, 336], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Load LoRA' },
              widgets_values: [lora_name ? 'On' : 'Off', lora_name, lora_weight, lora_clip],
            },
          ],
          links: [
            [175, 77, 0, 72, 0, 'IMAGE'],
            [176, 72, 0, 71, 2, 'IMAGE'],
            [188, 83, 0, 79, 0, 'CONDITIONING'],
            [189, 84, 0, 79, 1, 'CONDITIONING'],
            [204, 93, 0, 94, 1, 'VAE'],
            [217, 80, 2, 91, 1, 'VAE'],
            [245, 79, 0, 117, 0, '*'],
            [246, 79, 1, 118, 0, '*'],
            [278, 72, 0, 91, 0, 'IMAGE'],
            [287, 145, 0, 84, 1, 'STRING'],
            [309, 94, 0, 148, 0, 'IMAGE'],
            [321, 90, 0, 157, 0, 'MODEL'],
            [322, 117, 0, 157, 1, 'CONDITIONING'],
            [323, 118, 0, 157, 2, 'CONDITIONING'],
            [324, 91, 0, 157, 3, 'LATENT'],
            [325, 157, 0, 94, 0, 'LATENT'],
            [326, 77, 0, 158, 0, 'IMAGE'],
            [327, 158, 0, 71, 0, 'IMAGE'],
            [328, 71, 0, 79, 2, 'CONTROL_NET_STACK'],
            [332, 80, 0, 160, 0, 'MODEL'],
            [333, 80, 1, 160, 1, 'CLIP'],
            [334, 160, 0, 90, 0, '*'],
            [335, 160, 1, 83, 0, 'CLIP'],
            [336, 160, 1, 84, 0, 'CLIP'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '157': { seed: 0, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
