export const indoor_3 = ({
  client_id,
  load_img,
  text,
  negative,
  ipadapter_obj,
  ipadapter_imgs,
  cn_strength,
  design_type,
  ipadapter_point,
  hd,
  sampler_name,
  scheduler,
}: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  let prompt = `interior, flower, indoors, tree, no humans, window, vase, Step into the realms of an 8k masterpiece wallpaper, a nexus of ultra-detail, high resolution, and impeccable shadow play, ${text.replaceAll(
    '，',
    ',',
  )}`;
  const negative_prompt = `sky, cloud, blue_sky, scenery` + negative.replaceAll('，', ',');
  console.log('indoor_3', {
    client_id,
    load_img,
    text,
    negative,
    ipadapter_obj,
    ipadapter_imgs,
    cn_strength,
    input_seed,
    prompt,
    negative_prompt,
    design_type,
    ipadapter_point,
    sampler_name,
    scheduler,
  });
  return {
    client_id: client_id,
    prompt: {
      '70': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_canny.pth',
          controlnet_strength_1: 2,
          start_percent_1: 0,
          end_percent_1: 0.1,
          switch_2: 'Off',
          controlnet_2: 'control_v11p_sd15_soft.pth',
          controlnet_strength_2: 0.5,
          start_percent_2: 0,
          end_percent_2: 0.6,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.3,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_3: ['75', 0],
          controlnet_stack: ['71', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '71': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_mlsd.pth',
          controlnet_strength_1: 2,
          start_percent_1: 0,
          end_percent_1: 0.1,
          switch_2: 'On',
          controlnet_2: 'control_v11p_sd15_seg.pth',
          controlnet_strength_2: 0.5,
          start_percent_2: 0,
          end_percent_2: 0.5,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_3: cn_strength.strength,
          start_percent_3: 0,
          end_percent_3: cn_strength.end,
          image_2: ['76', 0],
          image_3: ['72', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '72': {
        inputs: { coarse: 'disable', resolution: 768, image: ['77', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '75': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '76': {
        inputs: { resolution: 512, image: ['77', 0] },
        class_type: 'OneFormer-COCO-SemSegPreprocessor',
      },
      '77': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '79': {
        inputs: {
          switch: 'On',
          base_positive: ['83', 0],
          base_negative: ['84', 0],
          controlnet_stack: ['100', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '80': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
      '81': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 0.5,
          clip_weight_1: 2,
          switch_2: 'Off',
          lora_name_2: 'Eva-GT.safetensors',
          model_weight_2: 0.25,
          clip_weight_2: 2,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 0.5,
          clip_weight_3: 2,
        },
        class_type: 'CR LoRA Stack',
      },
      '82': {
        inputs: { model: ['107', 0], clip: ['80', 1], lora_stack: ['103', 0] },
        class_type: 'CR Apply LoRA Stack',
      },
      '83': { inputs: { text: ['153', 0], clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
      '84': { inputs: { text: ['145', 0], clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
      '86': {
        inputs: { ipadapter_file: ipadapter_obj.ip_adapter },
        class_type: 'IPAdapterModelLoader',
      },
      '89': {
        inputs: {
          seed: input_seed,
          steps: 20,
          cfg: 7,
          sampler_name: sampler_name,
          scheduler: scheduler,
          denoise: 1,
          model: ['82', 0],
          positive: ['79', 0],
          negative: ['79', 1],
          latent_image: ['91', 0],
        },
        class_type: 'KSampler',
      },
      '91': { inputs: { pixels: ['72', 0], vae: ['80', 2] }, class_type: 'VAEEncode' },
      '93': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '94': { inputs: { samples: ['89', 0], vae: ['93', 0] }, class_type: 'VAEDecode' },
      '100': {
        inputs: {
          switch_1: 'Off',
          controlnet_1: 'control_v11p_sd15_normalbae.pth',
          controlnet_strength_1: 0.41000000000000003,
          start_percent_1: 0,
          end_percent_1: 0.6,
          switch_2: 'Off',
          controlnet_2: '图像融合.pth',
          controlnet_strength_2: 0.5700000000000001,
          start_percent_2: 0,
          end_percent_2: 1,
          switch_3: 'Off',
          controlnet_3: 'None',
          controlnet_strength_3: 1,
          start_percent_3: 0,
          end_percent_3: 1,
          controlnet_stack: ['70', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '103': {
        inputs: {
          switch_1: 'Off',
          lora_name_1: 'None',
          model_weight_1: 0.3,
          clip_weight_1: 1,
          switch_2: 'Off',
          lora_name_2: 'None',
          model_weight_2: 1,
          clip_weight_2: 1,
          switch_3: 'Off',
          lora_name_3: 'None',
          model_weight_3: 1,
          clip_weight_3: 1,
          lora_stack: ['81', 0],
        },
        class_type: 'CR LoRA Stack',
      },
      '104': {
        inputs: {
          ipadapter_plus: ipadapter_obj.plus,
          noise: 1,
          weight_1: 1,
          weight_2: 1,
          weight_3: 1,
          weight_4: 1,
          clip_vision: ['105', 0],
          image_1: ['109', 0],
        },
        class_type: 'IPAdapterEncoder',
      },
      '105': { inputs: { clip_name: 'SD1.5\\pytorch_model.bin' }, class_type: 'CLIPVisionLoader' },
      '107': {
        inputs: {
          weight: ipadapter_obj.plus ? 0.9 : 1,
          weight_type: 'original',
          start_at: 0,
          end_at: 1,
          unfold_batch: false,
          ipadapter: ['86', 0],
          embeds: ['104', 0],
          model: ['80', 0],
        },
        class_type: 'IPAdapterApplyEncoded',
      },
      '109': { inputs: { image: ipadapter_imgs[0].img, upload: 'image' }, class_type: 'LoadImage' },
      '116': {
        inputs: {
          upscale_by: 2,
          seed: 0,
          steps: 20,
          cfg: 8,
          sampler_name: 'euler_ancestral',
          scheduler: 'normal',
          denoise: 0.2,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['94', 0],
          model: ['82', 0],
          positive: ['79', 0],
          negative: ['79', 1],
          vae: ['93', 0],
          upscale_model: ['119', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '119': { inputs: { model_name: '8x_eva_super.pth' }, class_type: 'UpscaleModelLoader' },
      '145': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.75,
          append: true,
          text:
            'soft line,curved line,sketch,ugly,logo,pixelated,lowres,text,word,cropped,low quality,normal quality,username,watermark,signature,blurry,soft,' +
            negative_prompt,
        },
        class_type: 'EmbeddingPicker',
      },
      '152': {
        inputs: { image: '卫生间现代1 (1).jpeg', upload: 'image' },
        class_type: 'LoadImage',
      },
      '153': {
        inputs: {
          text: prompt,
        },
        class_type: 'CR Text',
      },
      '154': { inputs: { filename_prefix: 'Eva_AI', images: ['116', 0] }, class_type: 'SaveImage' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 154,
          last_link_id: 326,
          nodes: [
            {
              id: 105,
              type: 'CLIPVisionLoader',
              pos: [-3711, -835],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [
                { name: 'CLIP_VISION', type: 'CLIP_VISION', links: [225], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'CLIPVisionLoader' },
              widgets_values: ['SD1.5\\pytorch_model.bin'],
            },
            {
              id: 91,
              type: 'VAEEncode',
              pos: [-2249, 1247],
              size: { '0': 210.693603515625, '1': 65.94579315185547 },
              flags: {},
              order: 21,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 278 },
                { name: 'vae', type: 'VAE', link: 217, slot_index: 1 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [216], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 79,
              type: 'CR Apply Multi-ControlNet',
              pos: [-407, 762],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 29,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 188 },
                { name: 'base_negative', type: 'CONDITIONING', link: 189 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 212 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [245], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [246], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 82,
              type: 'CR Apply LoRA Stack',
              pos: [-2616, 85],
              size: { '0': 254.40000915527344, '1': 66 },
              flags: {},
              order: 24,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 232 },
                { name: 'clip', type: 'CLIP', link: 185 },
                { name: 'lora_stack', type: 'LORA_STACK', link: 224 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [196], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [186, 187], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
            },
            {
              id: 84,
              type: 'CLIPTextEncode',
              pos: [-2628, 460],
              size: { '0': 340.7228698730469, '1': 100.44314575195312 },
              flags: {},
              order: 28,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 187 },
                { name: 'text', type: 'STRING', link: 287, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [189],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 76,
              type: 'OneFormer-COCO-SemSegPreprocessor',
              pos: [-1970, 209],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 170 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [174], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'OneFormer-COCO-SemSegPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 100,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1041, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 25,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: null, slot_index: 1 },
                { name: 'image_3', type: 'IMAGE', link: null },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 211, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [212],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_normalbae.pth',
                0.41000000000000003,
                0,
                0.6,
                'Off',
                '图像融合.pth',
                0.5700000000000001,
                0,
                1,
                'Off',
                'None',
                1,
                0,
                1,
              ],
            },
            {
              id: 90,
              type: 'Reroute',
              pos: [-2582, 893],
              size: [75, 26],
              flags: {},
              order: 26,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 196 }],
              outputs: [{ name: '', type: 'MODEL', links: [197, 244, 304], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 117,
              type: 'Reroute',
              pos: [-2581, 967],
              size: [75, 26],
              flags: {},
              order: 30,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 245 }],
              outputs: [{ name: '', type: 'CONDITIONING', links: [248, 250, 305], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 118,
              type: 'Reroute',
              pos: [-2580, 1022],
              size: [75, 26],
              flags: {},
              order: 31,
              mode: 0,
              inputs: [{ name: '', type: '*', link: 246 }],
              outputs: [{ name: '', type: 'CONDITIONING', links: [249, 251, 306], slot_index: 0 }],
              properties: { showOutputText: false, horizontal: false },
            },
            {
              id: 93,
              type: 'VAELoader',
              pos: [-1867, 1001],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'VAE', type: 'VAE', links: [204, 247, 307], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 140,
              type: 'UltimateSDUpscale',
              pos: [-2693, 2217],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 35,
              mode: 4,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 280 },
                { name: 'model', type: 'MODEL', link: 304 },
                { name: 'positive', type: 'CONDITIONING', link: 305 },
                { name: 'negative', type: 'CONDITIONING', link: 306 },
                { name: 'vae', type: 'VAE', link: 307 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 308, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                2,
                0,
                'fixed',
                20,
                8,
                'euler_ancestral',
                'normal',
                0.1,
                'Linear',
                1024,
                1024,
                16,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 94,
              type: 'VAEDecode',
              pos: [-1402, 1240],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 33,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 203 },
                { name: 'vae', type: 'VAE', link: 204, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [243], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 111,
              type: 'LoadImage',
              pos: [-3906, -1221],
              size: { '0': 315, '1': 314 },
              flags: {},
              order: 2,
              mode: 4,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: ['9b6188de00b431f14c7ae72d4bb9d2a6 - 副本 (2).jpg', 'image'],
            },
            {
              id: 80,
              type: 'CheckpointLoaderSimple',
              pos: [-2641, -577],
              size: { '0': 315, '1': 98 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [231], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [185], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [217], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: ['Eva_AI.safetensors'],
            },
            {
              id: 83,
              type: 'CLIPTextEncode',
              pos: [-2627, 278],
              size: { '0': 342.46282958984375, '1': 114.1131362915039 },
              flags: {},
              order: 27,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 186 },
                { name: 'text', type: 'STRING', link: 322, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [188],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 70,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1502, 460],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 23,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: null },
                { name: 'image_3', type: 'IMAGE', link: 180 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 168, slot_index: 3 },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [211],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_canny.pth',
                2,
                0,
                0.1,
                'Off',
                'control_v11p_sd15_soft.pth',
                0.5,
                0,
                0.6,
                'On',
                'control_v11p_sd15_depth.pth',
                0.5,
                0,
                0.6,
              ],
            },
            {
              id: 119,
              type: 'UpscaleModelLoader',
              pos: [-3122, 1501],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                {
                  name: 'UPSCALE_MODEL',
                  type: 'UPSCALE_MODEL',
                  links: [253, 308],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'UpscaleModelLoader' },
              widgets_values: ['8x_eva_super.pth'],
            },
            {
              id: 151,
              type: 'WD14Tagger|pysssss',
              pos: [-3225, -15],
              size: { '0': 355.98284912109375, '1': 382.5198974609375 },
              flags: {},
              order: 18,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 317 }],
              outputs: [{ name: 'STRING', type: 'STRING', links: [], shape: 6, slot_index: 0 }],
              properties: { 'Node name for S&R': 'WD14Tagger|pysssss' },
              widgets_values: [
                'wd-v1-4-moat-tagger-v2',
                0.35000000000000003,
                0.85,
                false,
                false,
                '',
              ],
            },
            {
              id: 75,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1404, 211],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 172 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [180], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [512],
            },
            {
              id: 107,
              type: 'IPAdapterApplyEncoded',
              pos: [-2639, -856],
              size: { '0': 315, '1': 214 },
              flags: {},
              order: 22,
              mode: 0,
              inputs: [
                { name: 'ipadapter', type: 'IPADAPTER', link: 228 },
                { name: 'embeds', type: 'EMBEDS', link: 296 },
                { name: 'model', type: 'MODEL', link: 231, slot_index: 2 },
                { name: 'attn_mask', type: 'MASK', link: null },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [232], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'IPAdapterApplyEncoded' },
              widgets_values: [ipadapter_obj.plus ? 0.9 : 1, 'original', 0, 1, false],
            },
            {
              id: 86,
              type: 'IPAdapterModelLoader',
              pos: [-3717, -714],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'IPADAPTER', type: 'IPADAPTER', links: [228], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'IPAdapterModelLoader' },
              widgets_values: [ipadapter_obj.ip_adapter],
            },
            {
              id: 152,
              type: 'LoadImage',
              pos: [-3712, 23],
              size: { '0': 315, '1': 314 },
              flags: {},
              order: 6,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: ['卫生间现代1 (1).jpeg', 'image'],
            },
            {
              id: 104,
              type: 'IPAdapterEncoder',
              pos: [-3149, -851],
              size: { '0': 315, '1': 258 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'clip_vision', type: 'CLIP_VISION', link: 225, slot_index: 0 },
                { name: 'image_1', type: 'IMAGE', link: 325, slot_index: 1 },
                { name: 'image_2', type: 'IMAGE', link: null, slot_index: 2 },
                { name: 'image_3', type: 'IMAGE', link: 303, slot_index: 3 },
                { name: 'image_4', type: 'IMAGE', link: 300, slot_index: 4 },
              ],
              outputs: [{ name: 'EMBEDS', type: 'EMBEDS', links: [296], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'IPAdapterEncoder' },
              widgets_values: [ipadapter_obj.plus, 1, 1, 1, 1, 1],
            },
            {
              id: 145,
              type: 'EmbeddingPicker',
              pos: [-3165, 479],
              size: { '0': 400, '1': 200 },
              flags: {},
              order: 7,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [287], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.75,
                true,
                'soft line,curved line,sketch,ugly,logo,pixelated,lowres,text,word,cropped,low quality,normal quality,username,watermark,signature,blurry,soft,' +
                  negative_prompt,
              ],
            },
            {
              id: 71,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1994, 454],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: null },
                { name: 'image_2', type: 'IMAGE', link: 174 },
                { name: 'image_3', type: 'IMAGE', link: 176 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null, slot_index: 3 },
              ],
              outputs: [
                { name: 'CONTROLNET_STACK', type: 'CONTROL_NET_STACK', links: [168], shape: 3 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'Off',
                'control_v11p_sd15_mlsd.pth',
                2,
                0,
                0.1,
                'On',
                'control_v11p_sd15_seg.pth',
                0.5,
                0,
                0.5,
                'On',
                'control_v11p_sd15_lineart.pth',
                cn_strength.strength,
                0,
                cn_strength.end,
              ],
            },
            {
              id: 77,
              type: 'LoadImage',
              pos: [-1274, 1423],
              size: { '0': 612.6759033203125, '1': 692.9805297851562 },
              flags: {},
              order: 8,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [170, 172, 175], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 153,
              type: 'CR Text',
              pos: [-3243, -269],
              size: { '0': 400, '1': 200 },
              flags: {},
              order: 9,
              mode: 0,
              outputs: [
                { name: 'text', type: 'STRING', links: [322], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Text' },
              widgets_values: [prompt],
            },
            {
              id: 103,
              type: 'CR LoRA Stack',
              pos: [-2301, -377],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: 223 }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [224], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: ['Off', 'None', 0.3, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
            },
            {
              id: 81,
              type: 'CR LoRA Stack',
              pos: [-2649, -383],
              size: { '0': 315, '1': 342 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
              outputs: [
                { name: 'LORA_STACK', type: 'LORA_STACK', links: [223], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR LoRA Stack' },
              widgets_values: [
                'Off',
                'None',
                0.5,
                2,
                'Off',
                'Eva-GT.safetensors',
                0.25,
                2,
                'Off',
                'None',
                0.5,
                2,
              ],
            },
            {
              id: 112,
              type: 'LoadImage',
              pos: [-3932, -602],
              size: { '0': 353.93157958984375, '1': 342.38348388671875 },
              flags: {},
              order: 11,
              mode: 4,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [303], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: ['9b6188de00b431f14c7ae72d4bb9d2a6.jpg', 'image'],
            },
            {
              id: 110,
              type: 'LoadImage',
              pos: [-4292, -589],
              size: { '0': 315, '1': 314 },
              flags: {},
              order: 12,
              mode: 4,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [300], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: ['9b6188de00b431f14c7ae72d4bb9d2a6 - 副本 (3).jpg', 'image'],
            },
            {
              id: 109,
              type: 'LoadImage',
              pos: [-4284, -1220],
              size: { '0': 315, '1': 314 },
              flags: {},
              order: 13,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [317, 325], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [ipadapter_imgs[0].img, 'image'],
            },
            {
              id: 89,
              type: 'KSampler',
              pos: [-1851, 1112],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 32,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 197 },
                { name: 'positive', type: 'CONDITIONING', link: 248 },
                { name: 'negative', type: 'CONDITIONING', link: 249 },
                { name: 'latent_image', type: 'LATENT', link: 216, slot_index: 3 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [203], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', 20, 7, 'dpmpp_sde', 'karras', 1],
            },
            {
              id: 72,
              type: 'LineArtPreprocessor',
              pos: [-1684, 321],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 175 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [176, 278], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 116,
              type: 'UltimateSDUpscale',
              pos: [-2693, 1496],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 34,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 243 },
                { name: 'model', type: 'MODEL', link: 244 },
                { name: 'positive', type: 'CONDITIONING', link: 250 },
                { name: 'negative', type: 'CONDITIONING', link: 251 },
                { name: 'vae', type: 'VAE', link: 247 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 253, slot_index: 5 },
              ],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [280, 326], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                2,
                0,
                'fixed',
                20,
                8,
                'euler_ancestral',
                'normal',
                0.2,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 154,
              type: 'SaveImage',
              pos: [-2321, 1513],
              size: { '0': 493.20855712890625, '1': 403.7659606933594 },
              flags: {},
              order: 36,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 326 }],
              properties: {},
              widgets_values: ['Eva_AI'],
            },
          ],
          links: [
            [168, 71, 0, 70, 3, 'CONTROL_NET_STACK'],
            [170, 77, 0, 76, 0, 'IMAGE'],
            [172, 77, 0, 75, 0, 'IMAGE'],
            [174, 76, 0, 71, 1, 'IMAGE'],
            [175, 77, 0, 72, 0, 'IMAGE'],
            [176, 72, 0, 71, 2, 'IMAGE'],
            [180, 75, 0, 70, 2, 'IMAGE'],
            [185, 80, 1, 82, 1, 'CLIP'],
            [186, 82, 1, 83, 0, 'CLIP'],
            [187, 82, 1, 84, 0, 'CLIP'],
            [188, 83, 0, 79, 0, 'CONDITIONING'],
            [189, 84, 0, 79, 1, 'CONDITIONING'],
            [196, 82, 0, 90, 0, '*'],
            [197, 90, 0, 89, 0, 'MODEL'],
            [203, 89, 0, 94, 0, 'LATENT'],
            [204, 93, 0, 94, 1, 'VAE'],
            [211, 70, 0, 100, 3, 'CONTROL_NET_STACK'],
            [212, 100, 0, 79, 2, 'CONTROL_NET_STACK'],
            [216, 91, 0, 89, 3, 'LATENT'],
            [217, 80, 2, 91, 1, 'VAE'],
            [223, 81, 0, 103, 0, 'LORA_STACK'],
            [224, 103, 0, 82, 2, 'LORA_STACK'],
            [225, 105, 0, 104, 0, 'CLIP_VISION'],
            [228, 86, 0, 107, 0, 'IPADAPTER'],
            [231, 80, 0, 107, 2, 'MODEL'],
            [232, 107, 0, 82, 0, 'MODEL'],
            [243, 94, 0, 116, 0, 'IMAGE'],
            [244, 90, 0, 116, 1, 'MODEL'],
            [245, 79, 0, 117, 0, '*'],
            [246, 79, 1, 118, 0, '*'],
            [247, 93, 0, 116, 4, 'VAE'],
            [248, 117, 0, 89, 1, 'CONDITIONING'],
            [249, 118, 0, 89, 2, 'CONDITIONING'],
            [250, 117, 0, 116, 2, 'CONDITIONING'],
            [251, 118, 0, 116, 3, 'CONDITIONING'],
            [253, 119, 0, 116, 5, 'UPSCALE_MODEL'],
            [278, 72, 0, 91, 0, 'IMAGE'],
            [280, 116, 0, 140, 0, 'IMAGE'],
            [287, 145, 0, 84, 1, 'STRING'],
            [296, 104, 0, 107, 1, 'EMBEDS'],
            [300, 110, 0, 104, 4, 'IMAGE'],
            [303, 112, 0, 104, 3, 'IMAGE'],
            [304, 90, 0, 140, 1, 'MODEL'],
            [305, 117, 0, 140, 2, 'CONDITIONING'],
            [306, 118, 0, 140, 3, 'CONDITIONING'],
            [307, 93, 0, 140, 4, 'VAE'],
            [308, 119, 0, 140, 5, 'UPSCALE_MODEL'],
            [317, 109, 0, 151, 0, 'IMAGE'],
            [322, 153, 0, 83, 1, 'STRING'],
            [325, 109, 0, 104, 1, 'IMAGE'],
            [326, 116, 0, 154, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
        },
      },
    },
  };
};
