export const lockImg_color = ({ client_id, load_img, lock, text }: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  console.log({
    client_id,
    load_img,
    lock,
    text,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '4': { inputs: { text: ['46', 0], clip: ['6', 1] }, class_type: 'CLIPTextEncode' },
      '6': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_AI.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '7': { inputs: { text: ['8', 0], clip: ['6', 1] }, class_type: 'CLIPTextEncode' },
      '8': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '11': { inputs: { pixels: ['24', 0], vae: ['15', 0] }, class_type: 'VAEEncode' },
      '14': { inputs: { samples: ['47', 0], vae: ['15', 0] }, class_type: 'VAEDecode' },
      '15': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '24': {
        inputs: { size: 768, mode: false, images: ['35', 0] },
        class_type: 'ImageScaleDownToSize',
      },
      '27': {
        inputs: {
          switch_1: 'On',
          controlnet_1: 'control_v11p_sd15_lineart.pth',
          controlnet_strength_1: lock.line,
          start_percent_1: 0,
          end_percent_1: 1,
          switch_2: lock.open,
          controlnet_2: 'control_v11e_sd15_shuffle.pth',
          controlnet_strength_2: lock.weight,
          start_percent_2: 0,
          end_percent_2: lock.end,
          switch_3: 'On',
          controlnet_3: 'control_v11p_sd15_depth.pth',
          controlnet_strength_3: 0.3,
          start_percent_3: 0,
          end_percent_3: 0.6,
          image_1: ['29', 0],
          image_2: ['24', 0],
          image_3: ['31', 0],
        },
        class_type: 'CR Multi-ControlNet Stack',
      },
      '28': {
        inputs: {
          switch: 'On',
          base_positive: ['4', 0],
          base_negative: ['7', 0],
          controlnet_stack: ['27', 0],
        },
        class_type: 'CR Apply Multi-ControlNet',
      },
      '29': {
        inputs: { coarse: 'disable', resolution: 768, image: ['24', 0] },
        class_type: 'LineArtPreprocessor',
      },
      '30': { inputs: { resolution: 2048, image: ['24', 0] }, class_type: 'ColorPreprocessor' },
      '31': {
        inputs: { resolution: 768, image: ['24', 0] },
        class_type: 'Zoe-DepthMapPreprocessor',
      },
      '32': {
        inputs: {
          strength: 1,
          start_percent: 0,
          end_percent: 1,
          positive: ['28', 0],
          negative: ['28', 1],
          control_net: ['33', 0],
          image: ['30', 0],
        },
        class_type: 'ControlNetApplyAdvanced',
      },
      '33': {
        inputs: { control_net_name: 'control_v11p_sd15_lock.pth' },
        class_type: 'ControlNetLoader',
      },
      '34': {
        inputs: { a: 6.283185307179586, bg_threshold: 0.1, resolution: 768, image: ['24', 0] },
        class_type: 'MiDaS-NormalMapPreprocessor',
      },
      '35': {
        inputs: {
          upscale_model: '4x_foolhardy_Remacri.pth',
          mode: 'rescale',
          rescale_factor: 1.5,
          resize_width: 1024,
          resampling_method: 'lanczos',
          supersample: 'true',
          rounding_modulus: 8,
          image: ['1', 0],
        },
        class_type: 'CR Upscale Image',
      },
      '44': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_BirdsView.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '45': {
        inputs: { ratio: 0.05, model1: ['6', 0], model2: ['44', 0] },
        class_type: 'ModelMergeSimple',
      },
      '46': {
        inputs: {
          text: text,
        },
        class_type: 'CR Text',
      },
      '47': {
        inputs: {
          seed: input_seed,
          steps: 15,
          cfg: 5,
          sampler_name: 'euler_ancestral',
          scheduler: 'simple',
          denoise: 1,
          model: ['45', 0],
          positive: ['32', 0],
          negative: ['32', 1],
          latent_image: ['11', 0],
        },
        class_type: 'KSampler',
      },
      '49': { inputs: { filename_prefix: 'EvaAI', images: ['14', 0] }, class_type: 'SaveImage' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 49,
          last_link_id: 139,
          nodes: [
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [-1246, 879],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 5 },
                { name: 'text', type: 'STRING', link: 133, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [63],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [-1242, 1004],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 7 },
                { name: 'text', type: 'STRING', link: 6, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [64],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 29,
              type: 'LineArtPreprocessor',
              pos: [-1356, 184],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 14,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 67 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [68], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'LineArtPreprocessor' },
              widgets_values: ['disable', 768],
            },
            {
              id: 34,
              type: 'MiDaS-NormalMapPreprocessor',
              pos: [-1361, -67],
              size: { '0': 315, '1': 106 },
              flags: {},
              order: 16,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 90 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'MiDaS-NormalMapPreprocessor' },
              widgets_values: [6.283185307179586, 0.1, 768],
            },
            {
              id: 15,
              type: 'VAELoader',
              pos: [-752, 787],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [96, 98], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 32,
              type: 'ControlNetApplyAdvanced',
              pos: [-763, 391],
              size: { '0': 315, '1': 166 },
              flags: {},
              order: 20,
              mode: 0,
              inputs: [
                { name: 'positive', type: 'CONDITIONING', link: 75 },
                { name: 'negative', type: 'CONDITIONING', link: 76 },
                { name: 'control_net', type: 'CONTROL_NET', link: 74, slot_index: 2 },
                { name: 'image', type: 'IMAGE', link: 73 },
              ],
              outputs: [
                { name: 'positive', type: 'CONDITIONING', links: [135], shape: 3, slot_index: 0 },
                { name: 'negative', type: 'CONDITIONING', links: [136], shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'ControlNetApplyAdvanced' },
              widgets_values: [1, 0, 1],
            },
            {
              id: 31,
              type: 'Zoe-DepthMapPreprocessor',
              pos: [-1358, 83],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 15,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 71 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [108], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
              widgets_values: [768],
            },
            {
              id: 11,
              type: 'VAEEncode',
              pos: [-1001, 888],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 13,
              mode: 0,
              inputs: [
                { name: 'pixels', type: 'IMAGE', link: 27 },
                { name: 'vae', type: 'VAE', link: 98 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [137], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEEncode' },
            },
            {
              id: 28,
              type: 'CR Apply Multi-ControlNet',
              pos: [-769, 617],
              size: { '0': 330, '1': 98 },
              flags: {},
              order: 19,
              mode: 0,
              inputs: [
                { name: 'base_positive', type: 'CONDITIONING', link: 63 },
                { name: 'base_negative', type: 'CONDITIONING', link: 64 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 62 },
              ],
              outputs: [
                { name: 'base_pos', type: 'CONDITIONING', links: [75], shape: 3, slot_index: 0 },
                { name: 'base_neg', type: 'CONDITIONING', links: [76], shape: 3, slot_index: 1 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
              widgets_values: ['On'],
            },
            {
              id: 30,
              type: 'ColorPreprocessor',
              pos: [-763, 163],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 17,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 93 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [73], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ColorPreprocessor' },
              widgets_values: [2048],
            },
            {
              id: 44,
              type: 'CheckpointLoader',
              pos: [-2383, 462],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [123], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_BirdsView.safetensors'],
            },
            {
              id: 33,
              type: 'ControlNetLoader',
              pos: [-764, 283],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [{ name: 'CONTROL_NET', type: 'CONTROL_NET', links: [74], shape: 3 }],
              properties: { 'Node name for S&R': 'ControlNetLoader' },
              widgets_values: ['control_v11p_sd15_lock.pth'],
            },
            {
              id: 35,
              type: 'CR Upscale Image',
              pos: [-2640, 890],
              size: { '0': 315, '1': 222 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 84 }],
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [85], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 24,
              type: 'ImageScaleDownToSize',
              pos: [-2288, 856],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 85 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [51], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [768, false],
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [-2326, 1153],
              size: { '0': 363.5043029785156, '1': 365.5905456542969 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [84], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 17,
              type: 'CR Upscale Image',
              pos: [-1945, 849],
              size: { '0': 315, '1': 222 },
              flags: {},
              order: 12,
              mode: 4,
              inputs: [{ name: 'image', type: 'IMAGE', link: 51 }],
              outputs: [
                {
                  name: 'IMAGE',
                  type: 'IMAGE',
                  links: [27, 67, 71, 90, 93, 122],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Upscale Image' },
              widgets_values: [
                '4x_foolhardy_Remacri.pth',
                'rescale',
                1.5,
                1024,
                'lanczos',
                'true',
                8,
              ],
            },
            {
              id: 6,
              type: 'CheckpointLoader',
              pos: [-2014, 466],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [124], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [5, 7], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_AI.safetensors'],
            },
            {
              id: 27,
              type: 'CR Multi-ControlNet Stack',
              pos: [-1412, 329],
              size: { '0': 418.1999816894531, '1': 454 },
              flags: {},
              order: 18,
              mode: 0,
              inputs: [
                { name: 'image_1', type: 'IMAGE', link: 68 },
                { name: 'image_2', type: 'IMAGE', link: 122 },
                { name: 'image_3', type: 'IMAGE', link: 108 },
                { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null },
              ],
              outputs: [
                {
                  name: 'CONTROLNET_STACK',
                  type: 'CONTROL_NET_STACK',
                  links: [62],
                  shape: 3,
                  slot_index: 0,
                },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
              widgets_values: [
                'On',
                'control_v11p_sd15_lineart.pth',
                lock.line,
                0,
                1,
                lock.open,
                'control_v11e_sd15_shuffle.pth',
                lock.weight,
                0,
                lock.end,
                'On',
                'control_v11p_sd15_depth.pth',
                0.3,
                0,
                0.6,
              ],
            },
            {
              id: 45,
              type: 'ModelMergeSimple',
              pos: [-2216.537353515625, 650.7503967285156],
              size: { '0': 315, '1': 78 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [
                { name: 'model1', type: 'MODEL', link: 124 },
                { name: 'model2', type: 'MODEL', link: 123 },
              ],
              outputs: [{ name: 'MODEL', type: 'MODEL', links: [134], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ModelMergeSimple' },
              widgets_values: [0.05],
            },
            {
              id: 46,
              type: 'CR Text',
              pos: [-1839, 649],
              size: { '0': 333.9968566894531, '1': 135.4652099609375 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'text', type: 'STRING', links: [133], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Text' },
              widgets_values: [text],
            },
            {
              id: 47,
              type: 'KSampler',
              pos: [-990, 1006],
              size: { '0': 315, '1': 262 },
              flags: {},
              order: 21,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 134 },
                { name: 'positive', type: 'CONDITIONING', link: 135 },
                { name: 'negative', type: 'CONDITIONING', link: 136 },
                { name: 'latent_image', type: 'LATENT', link: 137 },
              ],
              outputs: [{ name: 'LATENT', type: 'LATENT', links: [138], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'KSampler' },
              widgets_values: [input_seed, 'randomize', 15, 5, 'euler_ancestral', 'simple', 1],
            },
            {
              id: 14,
              type: 'VAEDecode',
              pos: [-644, 953],
              size: { '0': 210, '1': 46 },
              flags: {},
              order: 22,
              mode: 0,
              inputs: [
                { name: 'samples', type: 'LATENT', link: 138 },
                { name: 'vae', type: 'VAE', link: 96, slot_index: 1 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [139], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAEDecode' },
            },
            {
              id: 49,
              type: 'SaveImage',
              pos: [-1960, 1161],
              size: [386.605224609375, 360.72637939453125],
              flags: {},
              order: 23,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 139 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
            {
              id: 8,
              type: 'EmbeddingPicker',
              pos: [-1555, 1107],
              size: { '0': 302.5414733886719, '1': 171.75250244140625 },
              flags: {},
              order: 6,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [6], shape: 3 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
          ],
          links: [
            [5, 6, 1, 4, 0, 'CLIP'],
            [6, 8, 0, 7, 1, 'STRING'],
            [7, 6, 1, 7, 0, 'CLIP'],
            [27, 17, 0, 11, 0, 'IMAGE'],
            [51, 24, 0, 17, 0, 'IMAGE'],
            [62, 27, 0, 28, 2, 'CONTROL_NET_STACK'],
            [63, 4, 0, 28, 0, 'CONDITIONING'],
            [64, 7, 0, 28, 1, 'CONDITIONING'],
            [67, 17, 0, 29, 0, 'IMAGE'],
            [68, 29, 0, 27, 0, 'IMAGE'],
            [71, 17, 0, 31, 0, 'IMAGE'],
            [73, 30, 0, 32, 3, 'IMAGE'],
            [74, 33, 0, 32, 2, 'CONTROL_NET'],
            [75, 28, 0, 32, 0, 'CONDITIONING'],
            [76, 28, 1, 32, 1, 'CONDITIONING'],
            [84, 1, 0, 35, 0, 'IMAGE'],
            [85, 35, 0, 24, 0, 'IMAGE'],
            [90, 17, 0, 34, 0, 'IMAGE'],
            [93, 17, 0, 30, 0, 'IMAGE'],
            [96, 15, 0, 14, 1, 'VAE'],
            [98, 15, 0, 11, 1, 'VAE'],
            [108, 31, 0, 27, 2, 'IMAGE'],
            [122, 17, 0, 27, 1, 'IMAGE'],
            [123, 44, 0, 45, 1, 'MODEL'],
            [124, 6, 0, 45, 0, 'MODEL'],
            [133, 46, 0, 4, 1, 'STRING'],
            [134, 45, 0, 47, 0, 'MODEL'],
            [135, 32, 0, 47, 1, 'CONDITIONING'],
            [136, 32, 1, 47, 2, 'CONDITIONING'],
            [137, 11, 0, 47, 3, 'LATENT'],
            [138, 47, 0, 14, 0, 'LATENT'],
            [139, 14, 0, 49, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '47': { seed: 0, sampler_name: 4, scheduler: 5 } },
        },
      },
    },
  };
};
