export const lockImg_upscale = ({ client_id, load_img, lock, text }: any) => {
  const input_seed = Math.floor(Math.random() * 1000000000000);
  console.log({
    client_id,
    load_img,
    text,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': { inputs: { image: load_img, upload: 'image' }, class_type: 'LoadImage' },
      '4': { inputs: { text: ['106', 0], clip: ['114', 1] }, class_type: 'CLIPTextEncode' },
      '6': {
        inputs: { config_name: 'anything_v3.yaml', ckpt_name: 'Eva_AI.safetensors' },
        class_type: 'CheckpointLoader',
      },
      '7': { inputs: { text: ['8', 0], clip: ['114', 1] }, class_type: 'CLIPTextEncode' },
      '8': {
        inputs: {
          embedding: 'EasyNegative.safetensors',
          emphasis: 0.85,
          append: true,
          text: 'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
        },
        class_type: 'EmbeddingPicker',
      },
      '15': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '105': { inputs: { filename_prefix: 'EvaAI', images: ['112', 0] }, class_type: 'SaveImage' },
      '106': {
        inputs: {
          prompt: text,
        },
        class_type: 'CR Prompt Text',
      },
      '112': {
        inputs: {
          upscale_by: 2,
          seed: input_seed,
          steps: 15,
          cfg: 6,
          sampler_name: 'euler_ancestral',
          scheduler: 'normal',
          denoise: 0.1,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['116', 0],
          model: ['114', 0],
          positive: ['4', 0],
          negative: ['7', 0],
          vae: ['15', 0],
          upscale_model: ['113', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '113': { inputs: { model_name: '8x_eva_super.pth' }, class_type: 'UpscaleModelLoader' },
      '114': {
        inputs: {
          lora_name: 'lcm-lora-sdv1-5.safetensors',
          strength_model: 1,
          strength_clip: 1,
          model: ['6', 0],
          clip: ['6', 1],
        },
        class_type: 'LoraLoader',
      },
      '116': {
        inputs: { size: 768, mode: false, images: ['1', 0] },
        class_type: 'ImageScaleDownToSize',
      },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 116,
          last_link_id: 253,
          nodes: [
            {
              id: 105,
              type: 'SaveImage',
              pos: [-636, 890],
              size: [430.7845127232596, 360.91951017013],
              flags: {},
              order: 11,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 245 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
            {
              id: 15,
              type: 'VAELoader',
              pos: [-993, 868],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [{ name: 'VAE', type: 'VAE', links: [244], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 7,
              type: 'CLIPTextEncode',
              pos: [-1260, 1011],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 250 },
                { name: 'text', type: 'STRING', link: 6, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [243],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [-1267, 877],
              size: { '0': 210, '1': 76.00001525878906 },
              flags: {},
              order: 8,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 249 },
                {
                  name: 'text',
                  type: 'STRING',
                  link: 236,
                  widget: { name: 'text' },
                  slot_index: 1,
                },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [242],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 8,
              type: 'EmbeddingPicker',
              pos: [-1598, 1044],
              size: { '0': 302.5414733886719, '1': 171.75250244140625 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [6], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: [
                'EasyNegative.safetensors',
                0.85,
                true,
                'lores, low resolution, low quality, anime, manga, comic, cartoon, thumbnai, artificial, plastic, imitation, fake, rendering, sketch',
              ],
            },
            {
              id: 106,
              type: 'CR Prompt Text',
              pos: [-1256, 1144],
              size: [210, 95.99999237060547],
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                { name: 'prompt', type: 'STRING', links: [236], shape: 3, slot_index: 0 },
                { name: 'show_help', type: 'STRING', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'CR Prompt Text' },
              widgets_values: [text],
            },
            {
              id: 113,
              type: 'UpscaleModelLoader',
              pos: [-1604, 1271],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 3,
              mode: 0,
              outputs: [{ name: 'UPSCALE_MODEL', type: 'UPSCALE_MODEL', links: [246], shape: 3 }],
              properties: { 'Node name for S&R': 'UpscaleModelLoader' },
              widgets_values: ['8x_eva_super.pth'],
            },
            {
              id: 114,
              type: 'LoraLoader',
              pos: [-1604, 867],
              size: { '0': 315, '1': 126 },
              flags: {},
              order: 6,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 247 },
                { name: 'clip', type: 'CLIP', link: 248 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [251], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [249, 250], shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'LoraLoader' },
              widgets_values: ['lcm-lora-sdv1-5.safetensors', 1, 1],
            },
            {
              id: 6,
              type: 'CheckpointLoader',
              pos: [-2011, 871],
              size: { '0': 336, '1': 122 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [247], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [248], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoader' },
              widgets_values: ['anything_v3.yaml', 'Eva_AI.safetensors'],
            },
            {
              id: 116,
              type: 'ImageScaleDownToSize',
              pos: [-1599, 1376],
              size: { '0': 315, '1': 82 },
              flags: {},
              order: 7,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 252 }],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [253], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'ImageScaleDownToSize' },
              widgets_values: [768, false],
            },
            {
              id: 112,
              type: 'UltimateSDUpscale',
              pos: [-988, 989],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 253 },
                { name: 'model', type: 'MODEL', link: 251 },
                { name: 'positive', type: 'CONDITIONING', link: 242 },
                { name: 'negative', type: 'CONDITIONING', link: 243 },
                { name: 'vae', type: 'VAE', link: 244 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 246, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [245], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                2,
                input_seed,
                'randomize',
                15,
                6,
                'euler_ancestral',
                'normal',
                0.2,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [-2015, 1055],
              size: { '0': 363.5043029785156, '1': 365.5905456542969 },
              flags: {},
              order: 5,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [252], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
          ],
          links: [
            [6, 8, 0, 7, 1, 'STRING'],
            [236, 106, 0, 4, 1, 'STRING'],
            [242, 4, 0, 112, 2, 'CONDITIONING'],
            [243, 7, 0, 112, 3, 'CONDITIONING'],
            [244, 15, 0, 112, 4, 'VAE'],
            [245, 112, 0, 105, 0, 'IMAGE'],
            [246, 113, 0, 112, 5, 'UPSCALE_MODEL'],
            [247, 6, 0, 114, 0, 'MODEL'],
            [248, 6, 1, 114, 1, 'CLIP'],
            [249, 114, 1, 4, 0, 'CLIP'],
            [250, 114, 1, 7, 0, 'CLIP'],
            [251, 114, 0, 112, 1, 'MODEL'],
            [252, 1, 0, 116, 0, 'IMAGE'],
            [253, 116, 0, 112, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: { '112': { seed: 1, sampler_name: 5, scheduler: 6 } },
        },
      },
    },
  };
};
