export const realUp = ({ client_id, load_img }: any) => {
  console.log({
    client_id,
    load_img,
  });
  return {
    client_id: client_id,
    prompt: {
      '1': {
        inputs: { image: load_img, upload: 'image' },
        class_type: 'LoadImage',
      },
      '2': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
      '3': {
        inputs: {
          upscale_by: 1,
          seed: 634727213409057,
          steps: 15,
          cfg: 7,
          sampler_name: 'dpmpp_sde',
          scheduler: 'karras',
          denoise: 0.12,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['1', 0],
          model: ['17', 0],
          positive: ['4', 0],
          negative: ['5', 0],
          vae: ['23', 0],
          upscale_model: ['15', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '4': { inputs: { text: ['27', 0], clip: ['17', 1] }, class_type: 'CLIPTextEncode' },
      '5': { inputs: { text: ['28', 0], clip: ['17', 1] }, class_type: 'CLIPTextEncode' },
      '15': { inputs: { model_name: '8x_eva_super.pth' }, class_type: 'UpscaleModelLoader' },
      '17': {
        inputs: {
          lora_name: 'lcm-lora-sdv1-5.safetensors',
          strength_model: 1,
          strength_clip: 1,
          model: ['2', 0],
          clip: ['2', 1],
        },
        class_type: 'LoraLoader',
      },
      '18': {
        inputs: {
          upscale_by: 1,
          seed: 532209422652416,
          steps: 15,
          cfg: 7,
          sampler_name: 'dpmpp_sde',
          scheduler: 'karras',
          denoise: 0.12,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['3', 0],
          model: ['17', 0],
          positive: ['4', 0],
          negative: ['5', 0],
          vae: ['23', 0],
          upscale_model: ['15', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '22': {
        inputs: {
          upscale_by: 1.2,
          seed: 6547629158586,
          steps: 15,
          cfg: 7,
          sampler_name: 'euler_ancestral',
          scheduler: 'normal',
          denoise: 0.12,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['18', 0],
          model: ['17', 0],
          positive: ['4', 0],
          negative: ['5', 0],
          vae: ['23', 0],
          upscale_model: ['15', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '23': {
        inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
        class_type: 'VAELoader',
      },
      '24': {
        inputs: {
          upscale_by: 1.2,
          seed: 967466287608366,
          steps: 15,
          cfg: 7,
          sampler_name: 'euler_ancestral',
          scheduler: 'normal',
          denoise: 0.12,
          mode_type: 'Linear',
          tile_width: 1024,
          tile_height: 1024,
          mask_blur: 8,
          tile_padding: 32,
          seam_fix_mode: 'None',
          seam_fix_denoise: 1,
          seam_fix_width: 64,
          seam_fix_mask_blur: 8,
          seam_fix_padding: 16,
          force_uniform_tiles: true,
          tiled_decode: false,
          image: ['22', 0],
          model: ['17', 0],
          positive: ['4', 0],
          negative: ['5', 0],
          vae: ['23', 0],
          upscale_model: ['15', 0],
        },
        class_type: 'UltimateSDUpscale',
      },
      '27': {
        inputs: {
          model: 'wd-v1-4-moat-tagger-v2',
          threshold: 0.2,
          character_threshold: 0.85,
          replace_underscore: false,
          trailing_comma: false,
          exclude_tags: '',
          tags: 'outdoors, sky, day, cloud, tree, blue_sky, no_humans, from_above, grass, ground_vehicle, building, scenery, motor_vehicle, city, car, road, cityscape, bridge, street, skyscraper, real_world_location',
          image: ['1', 0],
        },
        class_type: 'WD14Tagger|pysssss',
      },
      '28': {
        inputs: { embedding: 'EasyNegative.safetensors', emphasis: 1, append: false, text: '' },
        class_type: 'EmbeddingPicker',
      },
      '32': { inputs: { filename_prefix: 'EvaAI', images: ['24', 0] }, class_type: 'SaveImage' },
    },
    extra_data: {
      extra_pnginfo: {
        workflow: {
          last_node_id: 32,
          last_link_id: 50,
          nodes: [
            {
              id: 2,
              type: 'CheckpointLoaderSimple',
              pos: [2094, 600],
              size: { '0': 315, '1': 98 },
              flags: {},
              order: 0,
              mode: 0,
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [16], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [17], shape: 3, slot_index: 1 },
                { name: 'VAE', type: 'VAE', links: [], shape: 3, slot_index: 2 },
              ],
              properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
              widgets_values: ['Eva_AI.safetensors'],
            },
            {
              id: 17,
              type: 'LoraLoader',
              pos: [2074, 412],
              size: { '0': 315, '1': 126 },
              flags: {},
              order: 5,
              mode: 0,
              inputs: [
                { name: 'model', type: 'MODEL', link: 16 },
                { name: 'clip', type: 'CLIP', link: 17 },
              ],
              outputs: [
                { name: 'MODEL', type: 'MODEL', links: [20, 22, 33, 41], shape: 3, slot_index: 0 },
                { name: 'CLIP', type: 'CLIP', links: [18, 19], shape: 3, slot_index: 1 },
              ],
              properties: { 'Node name for S&R': 'LoraLoader' },
              widgets_values: ['lcm-lora-sdv1-5.safetensors', 1, 1],
            },
            {
              id: 23,
              type: 'VAELoader',
              pos: [2055, -19],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 1,
              mode: 0,
              outputs: [
                { name: 'VAE', type: 'VAE', links: [30, 31, 32, 39], shape: 3, slot_index: 0 },
              ],
              properties: { 'Node name for S&R': 'VAELoader' },
              widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
            },
            {
              id: 3,
              type: 'UltimateSDUpscale',
              pos: [2681, 282],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 9,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 3 },
                { name: 'model', type: 'MODEL', link: 20 },
                { name: 'positive', type: 'CONDITIONING', link: 5 },
                { name: 'negative', type: 'CONDITIONING', link: 7 },
                { name: 'vae', type: 'VAE', link: 30 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 11, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [21], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                1,
                634727213409057,
                'randomize',
                15,
                7,
                'dpmpp_sde',
                'karras',
                0.12,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 4,
              type: 'CLIPTextEncode',
              pos: [2149, 99],
              size: [220.97932128906268, 97.25241088867188],
              flags: { collapsed: false },
              order: 8,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 19 },
                { name: 'text', type: 'STRING', link: 44, widget: { name: 'text' }, slot_index: 1 },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [5, 23, 28, 37],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [
                'Aerial view showcasing a bustling urban landscape with modern skyscrapers, busy highways, and lush parks, highlighting a vibrant city life',
              ],
            },
            {
              id: 24,
              type: 'UltimateSDUpscale',
              pos: [3835, 281],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 12,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 42 },
                { name: 'model', type: 'MODEL', link: 41 },
                { name: 'positive', type: 'CONDITIONING', link: 37 },
                { name: 'negative', type: 'CONDITIONING', link: 38 },
                { name: 'vae', type: 'VAE', link: 39 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 40, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [50], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                1.2,
                967466287608366,
                'randomize',
                15,
                7,
                'euler_ancestral',
                'normal',
                0.12,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 18,
              type: 'UltimateSDUpscale',
              pos: [3081, 278],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 10,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 21 },
                { name: 'model', type: 'MODEL', link: 22 },
                { name: 'positive', type: 'CONDITIONING', link: 23 },
                { name: 'negative', type: 'CONDITIONING', link: 24 },
                { name: 'vae', type: 'VAE', link: 31 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 34, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [27], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                1,
                532209422652416,
                'randomize',
                15,
                7,
                'dpmpp_sde',
                'karras',
                0.12,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 5,
              type: 'CLIPTextEncode',
              pos: [2145, 268],
              size: [240.19970703125, 76],
              flags: { collapsed: false },
              order: 7,
              mode: 0,
              inputs: [
                { name: 'clip', type: 'CLIP', link: 18 },
                { name: 'text', type: 'STRING', link: 46, widget: { name: 'text' } },
              ],
              outputs: [
                {
                  name: 'CONDITIONING',
                  type: 'CONDITIONING',
                  links: [7, 24, 29, 38],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'CLIPTextEncode' },
              widgets_values: [''],
            },
            {
              id: 15,
              type: 'UpscaleModelLoader',
              pos: [1678, 247],
              size: { '0': 315, '1': 58 },
              flags: {},
              order: 2,
              mode: 0,
              outputs: [
                {
                  name: 'UPSCALE_MODEL',
                  type: 'UPSCALE_MODEL',
                  links: [11, 34, 35, 40],
                  shape: 3,
                  slot_index: 0,
                },
              ],
              properties: { 'Node name for S&R': 'UpscaleModelLoader' },
              widgets_values: ['8x_eva_super.pth'],
            },
            {
              id: 28,
              type: 'EmbeddingPicker',
              pos: [1692, 373],
              size: [290.4472515011621, 147.9999876022339],
              flags: {},
              order: 3,
              mode: 0,
              outputs: [{ name: 'text', type: 'STRING', links: [46], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'EmbeddingPicker' },
              widgets_values: ['EasyNegative.safetensors', 1, false, ''],
            },
            {
              id: 32,
              type: 'SaveImage',
              pos: [4197, -508],
              size: [637.5276601562491, 481.6679560546871],
              flags: {},
              order: 13,
              mode: 0,
              inputs: [{ name: 'images', type: 'IMAGE', link: 50 }],
              properties: {},
              widgets_values: ['EvaAI'],
            },
            {
              id: 22,
              type: 'UltimateSDUpscale',
              pos: [3462, 282],
              size: { '0': 315, '1': 614 },
              flags: {},
              order: 11,
              mode: 0,
              inputs: [
                { name: 'image', type: 'IMAGE', link: 27 },
                { name: 'model', type: 'MODEL', link: 33 },
                { name: 'positive', type: 'CONDITIONING', link: 28 },
                { name: 'negative', type: 'CONDITIONING', link: 29 },
                { name: 'vae', type: 'VAE', link: 32 },
                { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 35, slot_index: 5 },
              ],
              outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [42], shape: 3, slot_index: 0 }],
              properties: { 'Node name for S&R': 'UltimateSDUpscale' },
              widgets_values: [
                1.2,
                6547629158586,
                'randomize',
                15,
                7,
                'euler_ancestral',
                'normal',
                0.12,
                'Linear',
                1024,
                1024,
                8,
                32,
                'None',
                1,
                64,
                8,
                16,
                true,
                false,
              ],
            },
            {
              id: 1,
              type: 'LoadImage',
              pos: [2085, 781],
              size: { '0': 522.2883911132812, '1': 677.3435668945312 },
              flags: {},
              order: 4,
              mode: 0,
              outputs: [
                { name: 'IMAGE', type: 'IMAGE', links: [3, 45], shape: 3, slot_index: 0 },
                { name: 'MASK', type: 'MASK', links: null, shape: 3 },
              ],
              properties: { 'Node name for S&R': 'LoadImage' },
              widgets_values: [load_img, 'image'],
            },
            {
              id: 27,
              type: 'WD14Tagger|pysssss',
              pos: [1654, -54],
              size: [330.2720261250645, 248.57667175797383],
              flags: {},
              order: 6,
              mode: 0,
              inputs: [{ name: 'image', type: 'IMAGE', link: 45 }],
              outputs: [{ name: 'STRING', type: 'STRING', links: [44], shape: 6 }],
              properties: { 'Node name for S&R': 'WD14Tagger|pysssss' },
              widgets_values: [
                'wd-v1-4-moat-tagger-v2',
                0.2,
                0.85,
                false,
                false,
                '',
                'outdoors, sky, day, cloud, tree, blue_sky, no_humans, from_above, grass, ground_vehicle, building, scenery, motor_vehicle, city, car, road, cityscape, bridge, street, skyscraper, real_world_location',
              ],
            },
          ],
          links: [
            [3, 1, 0, 3, 0, 'IMAGE'],
            [5, 4, 0, 3, 2, 'CONDITIONING'],
            [7, 5, 0, 3, 3, 'CONDITIONING'],
            [11, 15, 0, 3, 5, 'UPSCALE_MODEL'],
            [16, 2, 0, 17, 0, 'MODEL'],
            [17, 2, 1, 17, 1, 'CLIP'],
            [18, 17, 1, 5, 0, 'CLIP'],
            [19, 17, 1, 4, 0, 'CLIP'],
            [20, 17, 0, 3, 1, 'MODEL'],
            [21, 3, 0, 18, 0, 'IMAGE'],
            [22, 17, 0, 18, 1, 'MODEL'],
            [23, 4, 0, 18, 2, 'CONDITIONING'],
            [24, 5, 0, 18, 3, 'CONDITIONING'],
            [27, 18, 0, 22, 0, 'IMAGE'],
            [28, 4, 0, 22, 2, 'CONDITIONING'],
            [29, 5, 0, 22, 3, 'CONDITIONING'],
            [30, 23, 0, 3, 4, 'VAE'],
            [31, 23, 0, 18, 4, 'VAE'],
            [32, 23, 0, 22, 4, 'VAE'],
            [33, 17, 0, 22, 1, 'MODEL'],
            [34, 15, 0, 18, 5, 'UPSCALE_MODEL'],
            [35, 15, 0, 22, 5, 'UPSCALE_MODEL'],
            [37, 4, 0, 24, 2, 'CONDITIONING'],
            [38, 5, 0, 24, 3, 'CONDITIONING'],
            [39, 23, 0, 24, 4, 'VAE'],
            [40, 15, 0, 24, 5, 'UPSCALE_MODEL'],
            [41, 17, 0, 24, 1, 'MODEL'],
            [42, 22, 0, 24, 0, 'IMAGE'],
            [44, 27, 0, 4, 1, 'STRING'],
            [45, 1, 0, 27, 0, 'IMAGE'],
            [46, 28, 0, 5, 1, 'STRING'],
            [50, 24, 0, 32, 0, 'IMAGE'],
          ],
          groups: [],
          config: {},
          extra: {},
          version: 0.4,
          widget_idx_map: {
            '3': { seed: 1, sampler_name: 5, scheduler: 6 },
            '18': { seed: 1, sampler_name: 5, scheduler: 6 },
            '22': { seed: 1, sampler_name: 5, scheduler: 6 },
            '24': { seed: 1, sampler_name: 5, scheduler: 6 },
          },
        },
      },
    },
  };
};
