const a = {
  client_id: '3ea12cd387fd4370b45a395c3dbb7067',
  prompt: {
    '70': {
      inputs: {
        switch_1: 'Off',
        controlnet_1: 'control_v11p_sd15_canny.pth',
        controlnet_strength_1: 1,
        start_percent_1: 0,
        end_percent_1: 1,
        switch_2: 'Off',
        controlnet_2: 'control_v11p_sd15_soft.pth',
        controlnet_strength_2: 0.5,
        start_percent_2: 0,
        end_percent_2: 0.6,
        switch_3: 'On',
        controlnet_3: 'control_v11p_sd15_depth.pth',
        controlnet_strength_3: 0.15,
        start_percent_3: 0,
        end_percent_3: 0.6,
        image_1: ['73', 0],
        image_2: ['73', 0],
        image_3: ['75', 0],
        controlnet_stack: ['71', 0],
      },
      class_type: 'CR Multi-ControlNet Stack',
    },
    '71': {
      inputs: {
        switch_1: 'Off',
        controlnet_1: 'control_v11p_sd15_mlsd.pth',
        controlnet_strength_1: 0.3,
        start_percent_1: 0,
        end_percent_1: 0.6,
        switch_2: 'On',
        controlnet_2: 'control_v11p_sd15_seg.pth',
        controlnet_strength_2: 0.15,
        start_percent_2: 0,
        end_percent_2: 0.6,
        switch_3: 'On',
        controlnet_3: 'control_v11p_sd15_lineart.pth',
        controlnet_strength_3: 0.6,
        start_percent_3: 0,
        end_percent_3: 0.6,
        image_1: ['74', 0],
        image_2: ['76', 0],
        image_3: ['72', 0],
      },
      class_type: 'CR Multi-ControlNet Stack',
    },
    '72': {
      inputs: { coarse: 'enable', resolution: 512, image: ['77', 0] },
      class_type: 'LineArtPreprocessor',
    },
    '73': {
      inputs: { low_threshold: 0.4, high_threshold: 0.8, image: ['77', 0] },
      class_type: 'Canny',
    },
    '74': {
      inputs: { score_threshold: 0.1, dist_threshold: 0.1, resolution: 512, image: ['77', 0] },
      class_type: 'M-LSDPreprocessor',
    },
    '75': { inputs: { resolution: 512, image: ['77', 0] }, class_type: 'Zoe-DepthMapPreprocessor' },
    '76': {
      inputs: { resolution: 512, image: ['77', 0] },
      class_type: 'OneFormer-COCO-SemSegPreprocessor',
    },
    '77': {
      inputs: { image: '微信图片_20240122121854.jpg', upload: 'image' },
      class_type: 'LoadImage',
    },
    '79': {
      inputs: {
        switch: 'On',
        base_positive: ['83', 0],
        base_negative: ['84', 0],
        controlnet_stack: ['100', 0],
      },
      class_type: 'CR Apply Multi-ControlNet',
    },
    '80': { inputs: { ckpt_name: 'Eva_AI.safetensors' }, class_type: 'CheckpointLoaderSimple' },
    '81': {
      inputs: {
        switch_1: 'On',
        lora_name_1: 'lcm-lora-sdv1-5.safetensors',
        model_weight_1: 1,
        clip_weight_1: 1,
        switch_2: 'Off',
        lora_name_2: 'QLCD-城市公园_V0.2.safetensors',
        model_weight_2: 0.5,
        clip_weight_2: 2,
        switch_3: 'Off',
        lora_name_3: 'ASTRA_Resident_Regular_V1 常规住宅_ASTRA常规住宅v1.0.safetensors',
        model_weight_3: 0.5,
        clip_weight_3: 2,
      },
      class_type: 'CR LoRA Stack',
    },
    '82': {
      inputs: { model: ['107', 0], clip: ['80', 1], lora_stack: ['103', 0] },
      class_type: 'CR Apply LoRA Stack',
    },
    '83': { inputs: { text: '', clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
    '84': { inputs: { text: '', clip: ['82', 1] }, class_type: 'CLIPTextEncode' },
    '86': { inputs: { ipadapter_file: 'ip_adapter-plus.bin' }, class_type: 'IPAdapterModelLoader' },
    '89': {
      inputs: {
        seed: 214778371802356,
        steps: 5,
        cfg: 1.9000000000000001,
        sampler_name: 'lcm',
        scheduler: 'normal',
        denoise: 1,
        model: ['82', 0],
        positive: ['79', 0],
        negative: ['79', 1],
        latent_image: ['91', 0],
      },
      class_type: 'KSampler',
    },
    '91': { inputs: { pixels: ['72', 0], vae: ['80', 2] }, class_type: 'VAEEncode' },
    '93': {
      inputs: { vae_name: '真实感vae-ft-mse-840000-ema-pruned_v10.0.pt' },
      class_type: 'VAELoader',
    },
    '94': { inputs: { samples: ['89', 0], vae: ['93', 0] }, class_type: 'VAEDecode' },
    '95': { inputs: { images: ['94', 0] }, class_type: 'PreviewImage' },
    '100': {
      inputs: {
        switch_1: 'On',
        controlnet_1: 'control_v11p_sd15_normalbae.pth',
        controlnet_strength_1: 0.15,
        start_percent_1: 0,
        end_percent_1: 0.6,
        switch_2: 'Off',
        controlnet_2: 'None',
        controlnet_strength_2: 1,
        start_percent_2: 0,
        end_percent_2: 1,
        switch_3: 'Off',
        controlnet_3: 'None',
        controlnet_strength_3: 1,
        start_percent_3: 0,
        end_percent_3: 1,
        image_1: ['101', 0],
        controlnet_stack: ['70', 0],
      },
      class_type: 'CR Multi-ControlNet Stack',
    },
    '101': {
      inputs: { resolution: 512, image: ['77', 0] },
      class_type: 'BAE-NormalMapPreprocessor',
    },
    '103': {
      inputs: {
        switch_1: 'Off',
        lora_name_1: 'None',
        model_weight_1: 1,
        clip_weight_1: 1,
        switch_2: 'Off',
        lora_name_2: 'None',
        model_weight_2: 1,
        clip_weight_2: 1,
        switch_3: 'Off',
        lora_name_3: 'None',
        model_weight_3: 1,
        clip_weight_3: 1,
        lora_stack: ['81', 0],
      },
      class_type: 'CR LoRA Stack',
    },
    '104': {
      inputs: {
        ipadapter_plus: true,
        noise: 1,
        weight_1: 1,
        weight_2: 1,
        weight_3: 1,
        weight_4: 1,
        clip_vision: ['105', 0],
        image_1: ['109', 0],
        image_2: ['111', 0],
      },
      class_type: 'IPAdapterEncoder',
    },
    '105': { inputs: { clip_name: 'SD1.5\\pytorch_model.bin' }, class_type: 'CLIPVisionLoader' },
    '106': {
      inputs: { embed1: ['104', 0], embed2: ['108', 0] },
      class_type: 'IPAdapterBatchEmbeds',
    },
    '107': {
      inputs: {
        weight: 1,
        weight_type: 'original',
        start_at: 0,
        end_at: 1,
        unfold_batch: false,
        ipadapter: ['86', 0],
        embeds: ['106', 0],
        model: ['80', 0],
      },
      class_type: 'IPAdapterApplyEncoded',
    },
    '108': {
      inputs: {
        ipadapter_plus: true,
        noise: 1,
        weight_1: 1,
        weight_2: 1,
        weight_3: 1,
        weight_4: 1,
        clip_vision: ['105', 0],
        image_1: ['110', 0],
        image_2: ['112', 0],
      },
      class_type: 'IPAdapterEncoder',
    },
    '109': {
      inputs: { image: '0fc783665160197e4ce61396b3a7217e (3).jpg', upload: 'image' },
      class_type: 'LoadImage',
    },
    '110': {
      inputs: { image: '0fc783665160197e4ce61396b3a7217e (2).jpg', upload: 'image' },
      class_type: 'LoadImage',
    },
    '111': {
      inputs: { image: 'b73d56498e4f9856b59c28f01da7a16e (8).jpg', upload: 'image' },
      class_type: 'LoadImage',
    },
    '112': {
      inputs: { image: '0a04f06360f10d18089b07e9ff381424 (2).jpg', upload: 'image' },
      class_type: 'LoadImage',
    },
    '114': { inputs: { images: ['72', 0] }, class_type: 'PreviewImage' },
    '115': { inputs: { images: ['94', 0] }, class_type: 'PreviewImage' },
    '119': { inputs: { model_name: '8x_eva_super.pth' }, class_type: 'UpscaleModelLoader' },
  },
  extra_data: {
    extra_pnginfo: {
      workflow: {
        last_node_id: 128,
        last_link_id: 270,
        nodes: [
          {
            id: 73,
            type: 'Canny',
            pos: [-1433, 56],
            size: { '0': 315, '1': 82 },
            flags: {},
            order: 16,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 171 }],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [178, 179], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'Canny' },
            widgets_values: [0.4, 0.8],
          },
          {
            id: 103,
            type: 'CR LoRA Stack',
            pos: [-2301, -377],
            size: { '0': 315, '1': 342 },
            flags: {},
            order: 11,
            mode: 0,
            inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: 223 }],
            outputs: [
              { name: 'LORA_STACK', type: 'LORA_STACK', links: [224], shape: 3, slot_index: 0 },
              { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
            ],
            properties: { 'Node name for S&R': 'CR LoRA Stack' },
            widgets_values: ['Off', 'None', 1, 1, 'Off', 'None', 1, 1, 'Off', 'None', 1, 1],
          },
          {
            id: 105,
            type: 'CLIPVisionLoader',
            pos: [-3711, -835],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 0,
            mode: 0,
            outputs: [
              {
                name: 'CLIP_VISION',
                type: 'CLIP_VISION',
                links: [225, 229],
                shape: 3,
                slot_index: 0,
              },
            ],
            properties: { 'Node name for S&R': 'CLIPVisionLoader' },
            widgets_values: ['SD1.5\\pytorch_model.bin'],
          },
          {
            id: 107,
            type: 'IPAdapterApplyEncoded',
            pos: [-2639, -856],
            size: { '0': 315, '1': 214 },
            flags: {},
            order: 24,
            mode: 0,
            inputs: [
              { name: 'ipadapter', type: 'IPADAPTER', link: 228 },
              { name: 'embeds', type: 'EMBEDS', link: 227 },
              { name: 'model', type: 'MODEL', link: 231, slot_index: 2 },
              { name: 'attn_mask', type: 'MASK', link: null },
            ],
            outputs: [{ name: 'MODEL', type: 'MODEL', links: [232], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'IPAdapterApplyEncoded' },
            widgets_values: [1, 'original', 0, 1, false],
          },
          {
            id: 84,
            type: 'CLIPTextEncode',
            pos: [-2630, 434],
            size: { '0': 340.7228698730469, '1': 100.44314575195312 },
            flags: {},
            order: 30,
            mode: 0,
            inputs: [{ name: 'clip', type: 'CLIP', link: 187 }],
            outputs: [
              { name: 'CONDITIONING', type: 'CONDITIONING', links: [189], shape: 3, slot_index: 0 },
            ],
            properties: { 'Node name for S&R': 'CLIPTextEncode' },
            widgets_values: [''],
          },
          {
            id: 106,
            type: 'IPAdapterBatchEmbeds',
            pos: [-2892, -901],
            size: { '0': 210, '1': 46 },
            flags: {},
            order: 20,
            mode: 0,
            inputs: [
              { name: 'embed1', type: 'EMBEDS', link: 226 },
              { name: 'embed2', type: 'EMBEDS', link: 230, slot_index: 1 },
            ],
            outputs: [{ name: 'EMBEDS', type: 'EMBEDS', links: [227], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'IPAdapterBatchEmbeds' },
          },
          {
            id: 76,
            type: 'OneFormer-COCO-SemSegPreprocessor',
            pos: [-1970, 209],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 15,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 170 }],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [174], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'OneFormer-COCO-SemSegPreprocessor' },
            widgets_values: [512],
          },
          {
            id: 75,
            type: 'Zoe-DepthMapPreprocessor',
            pos: [-1431, 213],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 17,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 172 }],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [180], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'Zoe-DepthMapPreprocessor' },
            widgets_values: [512],
          },
          {
            id: 81,
            type: 'CR LoRA Stack',
            pos: [-2655, -381],
            size: { '0': 315, '1': 342 },
            flags: {},
            order: 1,
            mode: 0,
            inputs: [{ name: 'lora_stack', type: 'LORA_STACK', link: null }],
            outputs: [
              { name: 'LORA_STACK', type: 'LORA_STACK', links: [223], shape: 3, slot_index: 0 },
              { name: 'show_help', type: 'STRING', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'CR LoRA Stack' },
            widgets_values: [
              'On',
              'lcm-lora-sdv1-5.safetensors',
              1,
              1,
              'Off',
              'QLCD-城市公园_V0.2.safetensors',
              0.5,
              2,
              'Off',
              'ASTRA_Resident_Regular_V1 常规住宅_ASTRA常规住宅v1.0.safetensors',
              0.5,
              2,
            ],
          },
          {
            id: 80,
            type: 'CheckpointLoaderSimple',
            pos: [-2641, -577],
            size: { '0': 315, '1': 98 },
            flags: {},
            order: 2,
            mode: 0,
            outputs: [
              { name: 'MODEL', type: 'MODEL', links: [231], shape: 3, slot_index: 0 },
              { name: 'CLIP', type: 'CLIP', links: [185], shape: 3, slot_index: 1 },
              { name: 'VAE', type: 'VAE', links: [217], shape: 3, slot_index: 2 },
            ],
            properties: { 'Node name for S&R': 'CheckpointLoaderSimple' },
            widgets_values: ['Eva_AI.safetensors'],
          },
          {
            id: 114,
            type: 'PreviewImage',
            pos: [-1789, -513],
            size: { '0': 518.5286254882812, '1': 416.2528381347656 },
            flags: {},
            order: 22,
            mode: 0,
            inputs: [{ name: 'images', type: 'IMAGE', link: 239 }],
            properties: { 'Node name for S&R': 'PreviewImage' },
          },
          {
            id: 74,
            type: 'M-LSDPreprocessor',
            pos: [-1970, 48],
            size: { '0': 315, '1': 106 },
            flags: {},
            order: 14,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 169, slot_index: 0 }],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [173], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'M-LSDPreprocessor' },
            widgets_values: [0.1, 0.1, 512],
          },
          {
            id: 101,
            type: 'BAE-NormalMapPreprocessor',
            pos: [-967, 208],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 19,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 213 }],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [214], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'BAE-NormalMapPreprocessor' },
            widgets_values: [512],
          },
          {
            id: 72,
            type: 'LineArtPreprocessor',
            pos: [-1684, 321],
            size: { '0': 315, '1': 82 },
            flags: {},
            order: 18,
            mode: 0,
            inputs: [{ name: 'image', type: 'IMAGE', link: 175 }],
            outputs: [
              { name: 'IMAGE', type: 'IMAGE', links: [176, 239, 241], shape: 3, slot_index: 0 },
            ],
            properties: { 'Node name for S&R': 'LineArtPreprocessor' },
            widgets_values: ['enable', 512],
          },
          {
            id: 119,
            type: 'UpscaleModelLoader',
            pos: [-3068, 1471],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 3,
            mode: 0,
            outputs: [{ name: 'UPSCALE_MODEL', type: 'UPSCALE_MODEL', links: [253], shape: 3 }],
            properties: { 'Node name for S&R': 'UpscaleModelLoader' },
            widgets_values: ['8x_eva_super.pth'],
          },
          {
            id: 79,
            type: 'CR Apply Multi-ControlNet',
            pos: [-407, 762],
            size: { '0': 330, '1': 98 },
            flags: {},
            order: 31,
            mode: 0,
            inputs: [
              { name: 'base_positive', type: 'CONDITIONING', link: 188 },
              { name: 'base_negative', type: 'CONDITIONING', link: 189 },
              { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 212 },
            ],
            outputs: [
              { name: 'base_pos', type: 'CONDITIONING', links: [245], shape: 3, slot_index: 0 },
              { name: 'base_neg', type: 'CONDITIONING', links: [246], shape: 3, slot_index: 1 },
              { name: 'show_help', type: 'STRING', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'CR Apply Multi-ControlNet' },
            widgets_values: ['On'],
          },
          {
            id: 116,
            type: 'UltimateSDUpscale',
            pos: [-2680, 1497],
            size: { '0': 315, '1': 614 },
            flags: {},
            order: 37,
            mode: 4,
            inputs: [
              { name: 'image', type: 'IMAGE', link: 243 },
              { name: 'model', type: 'MODEL', link: 244 },
              { name: 'positive', type: 'CONDITIONING', link: 250 },
              { name: 'negative', type: 'CONDITIONING', link: 251 },
              { name: 'vae', type: 'VAE', link: 247 },
              { name: 'upscale_model', type: 'UPSCALE_MODEL', link: 253, slot_index: 5 },
            ],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [252], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'UltimateSDUpscale' },
            widgets_values: [
              3,
              0,
              'fixed',
              20,
              8,
              'euler_ancestral',
              'normal',
              0.15,
              'Linear',
              1024,
              1024,
              16,
              32,
              'None',
              1,
              64,
              8,
              16,
              true,
              false,
            ],
          },
          {
            id: 117,
            type: 'Reroute',
            pos: [-2581, 967],
            size: [75, 26],
            flags: {},
            order: 32,
            mode: 0,
            inputs: [{ name: '', type: '*', link: 245 }],
            outputs: [{ name: '', type: 'CONDITIONING', links: [248, 250], slot_index: 0 }],
            properties: { showOutputText: false, horizontal: false },
          },
          {
            id: 118,
            type: 'Reroute',
            pos: [-2580, 1022],
            size: [75, 26],
            flags: {},
            order: 33,
            mode: 0,
            inputs: [{ name: '', type: '*', link: 246 }],
            outputs: [{ name: '', type: 'CONDITIONING', links: [249, 251], slot_index: 0 }],
            properties: { showOutputText: false, horizontal: false },
          },
          {
            id: 90,
            type: 'Reroute',
            pos: [-2582, 893],
            size: [75, 26],
            flags: {},
            order: 28,
            mode: 0,
            inputs: [{ name: '', type: '*', link: 196 }],
            outputs: [{ name: '', type: 'MODEL', links: [197, 244], slot_index: 0 }],
            properties: { showOutputText: false, horizontal: false },
          },
          {
            id: 93,
            type: 'VAELoader',
            pos: [-1867, 1001],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 4,
            mode: 0,
            outputs: [{ name: 'VAE', type: 'VAE', links: [204, 247], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'VAELoader' },
            widgets_values: ['真实感vae-ft-mse-840000-ema-pruned_v10.0.pt'],
          },
          {
            id: 82,
            type: 'CR Apply LoRA Stack',
            pos: [-2616, 85],
            size: { '0': 254.40000915527344, '1': 66 },
            flags: {},
            order: 26,
            mode: 0,
            inputs: [
              { name: 'model', type: 'MODEL', link: 232 },
              { name: 'clip', type: 'CLIP', link: 185 },
              { name: 'lora_stack', type: 'LORA_STACK', link: 224 },
            ],
            outputs: [
              { name: 'MODEL', type: 'MODEL', links: [196], shape: 3, slot_index: 0 },
              { name: 'CLIP', type: 'CLIP', links: [186, 187], shape: 3, slot_index: 1 },
              { name: 'show_help', type: 'STRING', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'CR Apply LoRA Stack' },
          },
          {
            id: 115,
            type: 'PreviewImage',
            pos: [-2344, 1536],
            size: { '0': 591.2793579101562, '1': 585.2994995117188 },
            flags: {},
            order: 36,
            mode: 0,
            inputs: [{ name: 'images', type: 'IMAGE', link: 242 }],
            properties: { 'Node name for S&R': 'PreviewImage' },
          },
          {
            id: 94,
            type: 'VAEDecode',
            pos: [-1356, 1246],
            size: { '0': 210, '1': 46 },
            flags: {},
            order: 35,
            mode: 0,
            inputs: [
              { name: 'samples', type: 'LATENT', link: 203 },
              { name: 'vae', type: 'VAE', link: 204, slot_index: 1 },
            ],
            outputs: [{ name: 'IMAGE', type: 'IMAGE', links: [242, 243], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'VAEDecode' },
          },
          {
            id: 100,
            type: 'CR Multi-ControlNet Stack',
            pos: [-1030, 457],
            size: { '0': 418.1999816894531, '1': 454 },
            flags: {},
            order: 27,
            mode: 0,
            inputs: [
              { name: 'image_1', type: 'IMAGE', link: 214 },
              { name: 'image_2', type: 'IMAGE', link: null },
              { name: 'image_3', type: 'IMAGE', link: null },
              { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 211, slot_index: 3 },
            ],
            outputs: [
              {
                name: 'CONTROLNET_STACK',
                type: 'CONTROL_NET_STACK',
                links: [212],
                shape: 3,
                slot_index: 0,
              },
              { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
            ],
            properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
            widgets_values: [
              'On',
              'control_v11p_sd15_normalbae.pth',
              0.15,
              0,
              0.6,
              'Off',
              'None',
              1,
              0,
              1,
              'Off',
              'None',
              1,
              0,
              1,
            ],
          },
          {
            id: 70,
            type: 'CR Multi-ControlNet Stack',
            pos: [-1502, 460],
            size: { '0': 418.1999816894531, '1': 454 },
            flags: {},
            order: 25,
            mode: 0,
            inputs: [
              { name: 'image_1', type: 'IMAGE', link: 178 },
              { name: 'image_2', type: 'IMAGE', link: 179 },
              { name: 'image_3', type: 'IMAGE', link: 180 },
              { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: 168, slot_index: 3 },
            ],
            outputs: [
              {
                name: 'CONTROLNET_STACK',
                type: 'CONTROL_NET_STACK',
                links: [211],
                shape: 3,
                slot_index: 0,
              },
              { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
            ],
            properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
            widgets_values: [
              'Off',
              'control_v11p_sd15_canny.pth',
              1,
              0,
              1,
              'Off',
              'control_v11p_sd15_soft.pth',
              0.5,
              0,
              0.6,
              'On',
              'control_v11p_sd15_depth.pth',
              0.15,
              0,
              0.6,
            ],
          },
          {
            id: 95,
            type: 'PreviewImage',
            pos: [-1744, 1524],
            size: { '0': 602.7257690429688, '1': 604.7886962890625 },
            flags: {},
            order: 38,
            mode: 0,
            inputs: [{ name: 'images', type: 'IMAGE', link: 252 }],
            properties: { 'Node name for S&R': 'PreviewImage' },
          },
          {
            id: 91,
            type: 'VAEEncode',
            pos: [-2249, 1247],
            size: [210.69360351562477, 65.94578968394876],
            flags: {},
            order: 23,
            mode: 0,
            inputs: [
              { name: 'pixels', type: 'IMAGE', link: 241 },
              { name: 'vae', type: 'VAE', link: 217, slot_index: 1 },
            ],
            outputs: [{ name: 'LATENT', type: 'LATENT', links: [216], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'VAEEncode' },
          },
          {
            id: 111,
            type: 'LoadImage',
            pos: [-3840, -1227],
            size: { '0': 315, '1': 314 },
            flags: {},
            order: 5,
            mode: 0,
            outputs: [
              { name: 'IMAGE', type: 'IMAGE', links: [235], shape: 3 },
              { name: 'MASK', type: 'MASK', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'LoadImage' },
            widgets_values: ['b73d56498e4f9856b59c28f01da7a16e (8).jpg', 'image'],
          },
          {
            id: 110,
            type: 'LoadImage',
            pos: [-4228, -601],
            size: { '0': 315, '1': 314 },
            flags: {},
            order: 6,
            mode: 0,
            outputs: [
              { name: 'IMAGE', type: 'IMAGE', links: [234], shape: 3 },
              { name: 'MASK', type: 'MASK', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'LoadImage' },
            widgets_values: ['0fc783665160197e4ce61396b3a7217e (2).jpg', 'image'],
          },
          {
            id: 109,
            type: 'LoadImage',
            pos: [-4224, -1214],
            size: { '0': 315, '1': 314 },
            flags: {},
            order: 7,
            mode: 0,
            outputs: [
              { name: 'IMAGE', type: 'IMAGE', links: [233], shape: 3 },
              { name: 'MASK', type: 'MASK', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'LoadImage' },
            widgets_values: ['0fc783665160197e4ce61396b3a7217e (3).jpg', 'image'],
          },
          {
            id: 112,
            type: 'LoadImage',
            pos: [-3818, -601],
            size: { '0': 353.93157958984375, '1': 342.38348388671875 },
            flags: {},
            order: 8,
            mode: 0,
            outputs: [
              { name: 'IMAGE', type: 'IMAGE', links: [236], shape: 3 },
              { name: 'MASK', type: 'MASK', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'LoadImage' },
            widgets_values: ['0a04f06360f10d18089b07e9ff381424 (2).jpg', 'image'],
          },
          {
            id: 89,
            type: 'KSampler',
            pos: [-1786, 1161],
            size: { '0': 315, '1': 262 },
            flags: {},
            order: 34,
            mode: 0,
            inputs: [
              { name: 'model', type: 'MODEL', link: 197 },
              { name: 'positive', type: 'CONDITIONING', link: 248 },
              { name: 'negative', type: 'CONDITIONING', link: 249 },
              { name: 'latent_image', type: 'LATENT', link: 216, slot_index: 3 },
            ],
            outputs: [{ name: 'LATENT', type: 'LATENT', links: [203], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'KSampler' },
            widgets_values: [214778371802356, 'fixed', 5, 1.9000000000000001, 'lcm', 'normal', 1],
          },
          {
            id: 71,
            type: 'CR Multi-ControlNet Stack',
            pos: [-1996, 460],
            size: { '0': 418.1999816894531, '1': 454 },
            flags: {},
            order: 21,
            mode: 0,
            inputs: [
              { name: 'image_1', type: 'IMAGE', link: 173 },
              { name: 'image_2', type: 'IMAGE', link: 174 },
              { name: 'image_3', type: 'IMAGE', link: 176 },
              { name: 'controlnet_stack', type: 'CONTROL_NET_STACK', link: null, slot_index: 3 },
            ],
            outputs: [
              { name: 'CONTROLNET_STACK', type: 'CONTROL_NET_STACK', links: [168], shape: 3 },
              { name: 'show_help', type: 'STRING', links: null, shape: 3, slot_index: 1 },
            ],
            properties: { 'Node name for S&R': 'CR Multi-ControlNet Stack' },
            widgets_values: [
              'Off',
              'control_v11p_sd15_mlsd.pth',
              0.3,
              0,
              0.6,
              'On',
              'control_v11p_sd15_seg.pth',
              0.15,
              0,
              0.6,
              'On',
              'control_v11p_sd15_lineart.pth',
              0.6,
              0,
              0.6,
            ],
          },
          {
            id: 83,
            type: 'CLIPTextEncode',
            pos: [-2630, 234],
            size: { '0': 342.46282958984375, '1': 114.1131362915039 },
            flags: {},
            order: 29,
            mode: 0,
            inputs: [{ name: 'clip', type: 'CLIP', link: 186 }],
            outputs: [
              { name: 'CONDITIONING', type: 'CONDITIONING', links: [188], shape: 3, slot_index: 0 },
            ],
            properties: { 'Node name for S&R': 'CLIPTextEncode' },
            widgets_values: [''],
          },
          {
            id: 77,
            type: 'LoadImage',
            pos: [-1130, 1502],
            size: { '0': 612.6759033203125, '1': 692.9805297851562 },
            flags: {},
            order: 9,
            mode: 0,
            outputs: [
              {
                name: 'IMAGE',
                type: 'IMAGE',
                links: [169, 170, 171, 172, 175, 213],
                shape: 3,
                slot_index: 0,
              },
              { name: 'MASK', type: 'MASK', links: null, shape: 3 },
            ],
            properties: { 'Node name for S&R': 'LoadImage' },
            widgets_values: ['微信图片_20240122121854.jpg', 'image'],
          },
          {
            id: 86,
            type: 'IPAdapterModelLoader',
            pos: [-3714, -730],
            size: { '0': 315, '1': 58 },
            flags: {},
            order: 10,
            mode: 0,
            outputs: [
              { name: 'IPADAPTER', type: 'IPADAPTER', links: [228], shape: 3, slot_index: 0 },
            ],
            properties: { 'Node name for S&R': 'IPAdapterModelLoader' },
            widgets_values: ['ip_adapter-plus.bin'],
          },
          {
            id: 108,
            type: 'IPAdapterEncoder',
            pos: [-3286, -796],
            size: { '0': 315, '1': 258 },
            flags: {},
            order: 13,
            mode: 0,
            inputs: [
              { name: 'clip_vision', type: 'CLIP_VISION', link: 229, slot_index: 0 },
              { name: 'image_1', type: 'IMAGE', link: 234, slot_index: 1 },
              { name: 'image_2', type: 'IMAGE', link: 236, slot_index: 2 },
              { name: 'image_3', type: 'IMAGE', link: null, slot_index: 3 },
              { name: 'image_4', type: 'IMAGE', link: null },
            ],
            outputs: [{ name: 'EMBEDS', type: 'EMBEDS', links: [230], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'IPAdapterEncoder' },
            widgets_values: [true, 1, 1, 1, 1, 1],
          },
          {
            id: 104,
            type: 'IPAdapterEncoder',
            pos: [-3289, -1111],
            size: { '0': 315, '1': 258 },
            flags: {},
            order: 12,
            mode: 0,
            inputs: [
              { name: 'clip_vision', type: 'CLIP_VISION', link: 225, slot_index: 0 },
              { name: 'image_1', type: 'IMAGE', link: 233, slot_index: 1 },
              { name: 'image_2', type: 'IMAGE', link: 235, slot_index: 2 },
              { name: 'image_3', type: 'IMAGE', link: null, slot_index: 3 },
              { name: 'image_4', type: 'IMAGE', link: null, slot_index: 4 },
            ],
            outputs: [{ name: 'EMBEDS', type: 'EMBEDS', links: [226], shape: 3, slot_index: 0 }],
            properties: { 'Node name for S&R': 'IPAdapterEncoder' },
            widgets_values: [true, 1, 1, 1, 1, 1],
          },
        ],
        links: [
          [168, 71, 0, 70, 3, 'CONTROL_NET_STACK'],
          [169, 77, 0, 74, 0, 'IMAGE'],
          [170, 77, 0, 76, 0, 'IMAGE'],
          [171, 77, 0, 73, 0, 'IMAGE'],
          [172, 77, 0, 75, 0, 'IMAGE'],
          [173, 74, 0, 71, 0, 'IMAGE'],
          [174, 76, 0, 71, 1, 'IMAGE'],
          [175, 77, 0, 72, 0, 'IMAGE'],
          [176, 72, 0, 71, 2, 'IMAGE'],
          [178, 73, 0, 70, 0, 'IMAGE'],
          [179, 73, 0, 70, 1, 'IMAGE'],
          [180, 75, 0, 70, 2, 'IMAGE'],
          [185, 80, 1, 82, 1, 'CLIP'],
          [186, 82, 1, 83, 0, 'CLIP'],
          [187, 82, 1, 84, 0, 'CLIP'],
          [188, 83, 0, 79, 0, 'CONDITIONING'],
          [189, 84, 0, 79, 1, 'CONDITIONING'],
          [196, 82, 0, 90, 0, '*'],
          [197, 90, 0, 89, 0, 'MODEL'],
          [203, 89, 0, 94, 0, 'LATENT'],
          [204, 93, 0, 94, 1, 'VAE'],
          [211, 70, 0, 100, 3, 'CONTROL_NET_STACK'],
          [212, 100, 0, 79, 2, 'CONTROL_NET_STACK'],
          [213, 77, 0, 101, 0, 'IMAGE'],
          [214, 101, 0, 100, 0, 'IMAGE'],
          [216, 91, 0, 89, 3, 'LATENT'],
          [217, 80, 2, 91, 1, 'VAE'],
          [223, 81, 0, 103, 0, 'LORA_STACK'],
          [224, 103, 0, 82, 2, 'LORA_STACK'],
          [225, 105, 0, 104, 0, 'CLIP_VISION'],
          [226, 104, 0, 106, 0, 'EMBEDS'],
          [227, 106, 0, 107, 1, 'EMBEDS'],
          [228, 86, 0, 107, 0, 'IPADAPTER'],
          [229, 105, 0, 108, 0, 'CLIP_VISION'],
          [230, 108, 0, 106, 1, 'EMBEDS'],
          [231, 80, 0, 107, 2, 'MODEL'],
          [232, 107, 0, 82, 0, 'MODEL'],
          [233, 109, 0, 104, 1, 'IMAGE'],
          [234, 110, 0, 108, 1, 'IMAGE'],
          [235, 111, 0, 104, 2, 'IMAGE'],
          [236, 112, 0, 108, 2, 'IMAGE'],
          [239, 72, 0, 114, 0, 'IMAGE'],
          [241, 72, 0, 91, 0, 'IMAGE'],
          [242, 94, 0, 115, 0, 'IMAGE'],
          [243, 94, 0, 116, 0, 'IMAGE'],
          [244, 90, 0, 116, 1, 'MODEL'],
          [245, 79, 0, 117, 0, '*'],
          [246, 79, 1, 118, 0, '*'],
          [247, 93, 0, 116, 4, 'VAE'],
          [248, 117, 0, 89, 1, 'CONDITIONING'],
          [249, 118, 0, 89, 2, 'CONDITIONING'],
          [250, 117, 0, 116, 2, 'CONDITIONING'],
          [251, 118, 0, 116, 3, 'CONDITIONING'],
          [252, 116, 0, 95, 0, 'IMAGE'],
          [253, 119, 0, 116, 5, 'UPSCALE_MODEL'],
        ],
        groups: [],
        config: {},
        extra: {},
        version: 0.4,
      },
    },
  },
};